// animais.js
export default [
    { 
        "nome": { "pt": "Leão", "en": "Lion" }, 
        "peso": 190, "dieta": "Carnivoro", 
        "habitat": ["terrestre"], "continentes": ["Africa"], 
        "classe": "Mamifero", "populacao": "Milhares" 
    },
    { 
        "nome": { "pt": "Elefante Africano", "en": "African Elephant" }, 
        "peso": 6000, "dieta": "Herbivoro", 
        "habitat": ["terrestre"], "continentes": ["Africa"], 
        "classe": "Mamifero", "populacao": "Milhares" 
    },
    { "nome": { "pt": "Baleia Azul", "en": "Blue Whale" }, "peso": 150000, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Formiga", "en": "Ant" }, "peso": 0.000005, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Inseto", "populacao": "Trilhões" },
    { "nome": { "pt": "Águia Careca", "en": "Bald Eagle" }, "peso": 5.5, "dieta": "Carnivoro", "habitat": ["aereo"], "continentes": ["America"], "classe": "Ave", "populacao": "Milhares" },
    { "nome": { "pt": "Tubarão Branco", "en": "Great White Shark" }, "peso": 1000, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Africa", "America", "Oceania"], "classe": "Peixe", "populacao": "Milhares" },
    { "nome": { "pt": "Capivara", "en": "Capybara" }, "peso": 50, "dieta": "Herbivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["America"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Pinguim de Magalhães", "en": "Magellanic Penguin" }, "peso": 4, "dieta": "Piscivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["America"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Dragão de Komodo", "en": "Komodo Dragon" }, "peso": 70, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["Asia"], "classe": "Reptil", "populacao": "Milhares" },
    { "nome": { "pt": "Sapo Cururu", "en": "Cane Toad" }, "peso": 1.3, "dieta": "Insetivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["America", "Oceania"], "classe": "Anfibio", "populacao": "Milhões" },
    { "nome": { "pt": "Abelha", "en": "Honey Bee" }, "peso": 0.0001, "dieta": "Herbivoro", "habitat": ["aereo"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Inseto", "populacao": "Trilhões" },
    { "nome": { "pt": "Canguru Vermelho", "en": "Red Kangaroo" }, "peso": 85, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Oceania"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Polvo Comum", "en": "Common Octopus" }, "peso": 5, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Asia", "Europa", "America"], "classe": "Molusco", "populacao": "Milhões" },
    { "nome": { "pt": "Tigre", "en": "Tiger" }, "peso": 220, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["Asia"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Mosquito", "en": "Mosquito" }, "peso": 0.000002, "dieta": "Hematofago", "habitat": ["aereo"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Inseto", "populacao": "Trilhões" },
    { "nome": { "pt": "Girafa", "en": "Giraffe" }, "peso": 1200, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Lobo Cinzento", "en": "Grey Wolf" }, "peso": 40, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["America", "Europa", "Asia"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Aranha Caranguejeira", "en": "Tarantula" }, "peso": 0.08, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["America"], "classe": "Aracnideo", "populacao": "Milhões" },
    { "nome": { "pt": "Salmão do Atlântico", "en": "Atlantic Salmon" }, "peso": 4, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["America", "Europa"], "classe": "Peixe", "populacao": "Milhões" },
    { "nome": { "pt": "Ornitorrinco", "en": "Platypus" }, "peso": 1.5, "dieta": "Carnivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["Oceania"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Avestruz", "en": "Ostrich" }, "peso": 140, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Urso Polar", "en": "Polar Bear" }, "peso": 450, "dieta": "Carnivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["America", "Europa", "Asia"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Camaleão", "en": "Chameleon" }, "peso": 0.1, "dieta": "Insetivoro", "habitat": ["terrestre"], "continentes": ["Africa", "Europa", "Asia"], "classe": "Reptil", "populacao": "Milhões" },
    { "nome": { "pt": "Crocodilo de Água Salgada", "en": "Saltwater Crocodile" }, "peso": 500, "dieta": "Carnivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["Asia", "Oceania"], "classe": "Reptil", "populacao": "Milhares" },
    { "nome": { "pt": "Gorila", "en": "Gorilla" }, "peso": 160, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Panda Gigante", "en": "Giant Panda" }, "peso": 100, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Asia"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Barata", "en": "Cockroach" }, "peso": 0.03, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Inseto", "populacao": "Bilhões" },
    { "nome": { "pt": "Beija-flor", "en": "Hummingbird" }, "peso": 0.004, "dieta": "Nectarivoro", "habitat": ["aereo"], "continentes": ["America"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Hipopótamo", "en": "Hippopotamus" }, "peso": 1500, "dieta": "Herbivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["Africa"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Caranguejo Eremita", "en": "Hermit Crab" }, "peso": 0.5, "dieta": "Onivoro", "habitat": ["terrestre", "aquatico"], "continentes": ["America", "Europa", "Asia"], "classe": "Crustaceo", "populacao": "Milhões" },
    { "nome": { "pt": "Escorpião Imperador", "en": "Emperor Scorpion" }, "peso": 0.03, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Aracnideo", "populacao": "Milhões" },
    { "nome": { "pt": "Cobra Real", "en": "King Cobra" }, "peso": 6, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["Asia"], "classe": "Reptil", "populacao": "Milhares" },
    { "nome": { "pt": "Vaca Doméstica", "en": "Cow" }, "peso": 720, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },
    { "nome": { "pt": "Cavalo-Marinho", "en": "Seahorse" }, "peso": 0.2, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["America", "Europa", "Asia"], "classe": "Peixe", "populacao": "Milhões" },
    { "nome": { "pt": "Tartaruga Verde", "en": "Green Sea Turtle" }, "peso": 160, "dieta": "Herbivoro", "habitat": ["aquatico"], "continentes": ["Africa", "Asia", "America", "Oceania"], "classe": "Reptil", "populacao": "Milhares" },
    { "nome": { "pt": "Axolote", "en": "Axolotl" }, "peso": 0.3, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["America"], "classe": "Anfibio", "populacao": "Milhares" },
    { "nome": { "pt": "Libélula", "en": "Dragonfly" }, "peso": 0.001, "dieta": "Carnivoro", "habitat": ["aereo"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Inseto", "populacao": "Bilhões" },
    { "nome": { "pt": "Caracol de Jardim", "en": "Garden Snail" }, "peso": 0.03, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Molusco", "populacao": "Bilhões" },
    { "nome": { "pt": "Orca", "en": "Killer Whale" }, "peso": 4000, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Africa", "Asia", "Europa", "America", "Oceania"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Preguiça", "en": "Sloth" }, "peso": 4.5, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["America"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Tucano", "en": "Toucan" }, "peso": 0.6, "dieta": "Onivoro", "habitat": ["aereo"], "continentes": ["America"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Peixe-Palhaço", "en": "Clownfish" }, "peso": 0.25, "dieta": "Onivoro", "habitat": ["aquatico"], "continentes": ["Asia", "Oceania"], "classe": "Peixe", "populacao": "Milhões" },
    { "nome": { "pt": "Rinoceronte Branco", "en": "White Rhinoceros" }, "peso": 2300, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Lula Colossal", "en": "Colossal Squid" }, "peso": 495, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Oceania", "America"], "classe": "Molusco", "populacao": "Milhares" },
    { "nome": { "pt": "Guepardo", "en": "Cheetah" }, "peso": 50, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["Africa", "Asia"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Borboleta Monarca", "en": "Monarch Butterfly" }, "peso": 0.0005, "dieta": "Herbivoro", "habitat": ["aereo"], "continentes": ["America"], "classe": "Inseto", "populacao": "Milhões" },
    { "nome": { "pt": "Baiacu", "en": "Pufferfish" }, "peso": 1, "dieta": "Onivoro", "habitat": ["aquatico"], "continentes": ["Asia", "America", "Africa"], "classe": "Peixe", "populacao": "Milhões" },
    { "nome": { "pt": "Salamandra Gigante", "en": "Giant Salamander" }, "peso": 25, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Asia"], "classe": "Anfibio", "populacao": "Milhares" },
    { "nome": { "pt": "Suricato", "en": "Meerkat" }, "peso": 0.75, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Pirarucu", "en": "Arapaima" }, "peso": 200, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["America"], "classe": "Peixe", "populacao": "Milhares" },
    { "nome": { "pt": "Lagosta Americana", "en": "American Lobster" }, "peso": 4, "dieta": "Onivoro", "habitat": ["aquatico"], "continentes": ["America"], "classe": "Crustaceo", "populacao": "Milhões" },
    { "nome": { "pt": "Lêmure", "en": "Lemur" }, "peso": 2.5, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Mamifero", "populacao": "Milhares" },
    { "nome": { "pt": "Coala", "en": "Koala" }, "peso": 9, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Oceania"], "classe": "Mamifero", "populacao": "Milhares" },

    { "nome": { "pt": "Gato Doméstico", "en": "Cat" }, "peso": 4, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },
    { "nome": { "pt": "Cachorro Doméstico", "en": "Dog" }, "peso": 20, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },
    { "nome": { "pt": "Galinha", "en": "Chicken" }, "peso": 2.5, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Ave", "populacao": "Bilhões" },
    { "nome": { "pt": "Pato", "en": "Duck" }, "peso": 1.5, "dieta": "Onivoro", "habitat": ["terrestre","aquatico"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Ganso", "en": "Goose" }, "peso": 4, "dieta": "Herbivoro", "habitat": ["terrestre","aquatico"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Cisne", "en": "Swan" }, "peso": 12, "dieta": "Herbivoro", "habitat": ["aquatico","terrestre"], "continentes": ["Europa","Asia","America","Oceania"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Porco", "en": "Pig" }, "peso": 110, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },
    { "nome": { "pt": "Javali", "en": "Wild Boar" }, "peso": 90, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Europa","Asia","Africa"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Ovelha", "en": "Sheep" }, "peso": 70, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Asia","Europa","America","Oceania","Africa"], "classe": "Mamifero", "populacao": "Bilhões" },
    { "nome": { "pt": "Cabra", "en": "Goat" }, "peso": 60, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },

    { "nome": { "pt": "Cavalo", "en": "Horse" }, "peso": 500, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Burro", "en": "Donkey" }, "peso": 250, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Camelo", "en": "Camel" }, "peso": 600, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Oceania"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Rato", "en": "Rat" }, "peso": 0.4, "dieta": "Onivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },
    { "nome": { "pt": "Morcego", "en": "Bat" }, "peso": 0.03, "dieta": "Insetivoro", "habitat": ["aereo"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Bilhões" },

    { "nome": { "pt": "Golfinho", "en": "Dolphin" }, "peso": 300, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Foca", "en": "Seal" }, "peso": 200, "dieta": "Carnivoro", "habitat": ["aquatico","terrestre"], "continentes": ["America","Europa","Asia"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Lontra", "en": "Otter" }, "peso": 14, "dieta": "Carnivoro", "habitat": ["aquatico","terrestre"], "continentes": ["America","Europa","Asia","Africa"], "classe": "Mamifero", "populacao": "Milhões" },
    { "nome": { "pt": "Jacaré", "en": "Alligator" }, "peso": 360, "dieta": "Carnivoro", "habitat": ["aquatico","terrestre"], "continentes": ["America"], "classe": "Reptil", "populacao": "Milhões" },

    { "nome": { "pt": "Coruja", "en": "Owl" }, "peso": 2, "dieta": "Carnivoro", "habitat": ["aereo"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Ave", "populacao": "Milhões" },
    { "nome": { "pt": "Papagaio", "en": "Parrot" }, "peso": 1, "dieta": "Herbivoro", "habitat": ["aereo"], "continentes": ["America","Oceania","Africa"], "classe": "Ave", "populacao": "Milhões" },

    { "nome": { "pt": "Sardinha", "en": "Sardine" }, "peso": 0.15, "dieta": "Onivoro", "habitat": ["aquatico"], "continentes": ["Africa","Europa","America"], "classe": "Peixe", "populacao": "Bilhões" },
    { "nome": { "pt": "Atum", "en": "Tuna" }, "peso": 250, "dieta": "Carnivoro", "habitat": ["aquatico"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Peixe", "populacao": "Milhões" },

    { "nome": { "pt": "Minhoca", "en": "Earthworm" }, "peso": 0.002, "dieta": "Detritivoro", "habitat": ["terrestre"], "continentes": ["Africa","Asia","Europa","America","Oceania"], "classe": "Anelideo", "populacao": "Bilhões" },

    // EXTINTOS
    { "nome": { "pt": "Tiranossauro Rex", "en": "Tyrannosaurus Rex" }, "peso": 8000, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["America"], "classe": "Reptil", "populacao": "Extinto" },
    { "nome": { "pt": "Mamute Lanoso", "en": "Woolly Mammoth" }, "peso": 6000, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Europa","Asia","America"], "classe": "Mamifero", "populacao": "Extinto" },
    { "nome": { "pt": "Dodô", "en": "Dodo" }, "peso": 15, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Africa"], "classe": "Ave", "populacao": "Extinto" },
    { "nome": { "pt": "Tigre-dente-de-sabre", "en": "Sabertooth Tiger" }, "peso": 300, "dieta": "Carnivoro", "habitat": ["terrestre"], "continentes": ["America"], "classe": "Mamifero", "populacao": "Extinto" },
    { "nome": { "pt": "Moa Gigante", "en": "Giant Moa" }, "peso": 230, "dieta": "Herbivoro", "habitat": ["terrestre"], "continentes": ["Oceania"], "classe": "Ave", "populacao": "Extinto" }
];
