// games/mindsync/palavras.js

export const palavrasPT = [
    //1. Objetos do cotidiano
    "Cadeira", "Mesa", "Sofá", "Cama", "Travesseiro", "Cobertor", "Almofada", "Armário", "Estante", "Prateleira",
    "Porta", "Janela", "Cortina", "Tapete", "Espelho", "Lâmpada", "Interruptor", "Tomada", "Ventilador", "Aquecedor",
    "Geladeira", "Freezer", "Fogão", "Forno", "Microondas", "Panela", "Frigideira", "Prato", "Copo", "Xícara",
    "Talher", "Faca", "Garfo", "Colher", "Tábua", "Liquidificador", "Batedeira", "Cafeteira", "Garrafa", "Pote",
    "Escova", "Pente", "Sabonete", "Shampoo", "Toalha", "Papel", "Caderno", "Livro", "Caneta", "Lápis",
    "Borracha", "Apontador", "Mochila", "Bolsa", "Carteira", "Chave", "Fechadura", "Relógio", "Celular", "Telefone",
    "Computador", "Teclado", "Mouse", "Monitor", "Impressora", "Carregador", "Fone", "Caixa", "Controle", "Televisão",
    "Rádio", "Câmera", "Óculos", "Guarda-chuva", "Boné", "Chapéu", "Camisa", "Calça", "Sapato", "Meia",
    "Cinto", "Casaco", "Jaqueta", "Escada", "Martelo", "Chave de fenda", "Alicate", "Vassoura", "Rodo", "Balde",
    "Pá", "Lixeira", "Saco", "Caixa de papelão", "Fita", "Tesoura", "Cola", "Envelope", "Calendário", "Agenda",
    //2. Comida
    "Arroz", "Feijão", "Carne", "Frango", "Peixe", "Ovo", "Pão", "Leite", "Queijo", "Manteiga",
    "Açúcar", "Sal", "Óleo", "Azeite", "Macarrão", "Pizza", "Hambúrguer", "Salsicha", "Linguiça", "Presunto",
    "Bacon", "Alface", "Tomate", "Cenoura", "Batata", "Cebola", "Alho", "Brócolis", "Couve", "Espinafre",
    "Milho", "Ervilha", "Arroz Integral", "Feijão Preto", "Lentilha", "Grão-de-bico", "Soja", "Cogumelo", "Abóbora", "Abobrinha",
    "Berinjela", "Pepino", "Pimentão", "Maçã", "Banana", "Laranja", "Uva", "Manga", "Morango", "Abacaxi",
    "Limão", "Melancia", "Melão", "Pera", "Mamão", "Kiwi", "Castanha", "Amendoim", "Noz", "Amêndoa",
    "Iogurte", "Requeijão", "Creme", "Sorvete", "Bolo", "Torta", "Biscoito", "Chocolate", "Doce", "Mel",
    "Geleia", "Pudim", "Mousse", "Brigadeiro", "Paçoca", "Cereal", "Aveia", "Farinha", "Trigo", "Milho Verde",
    "Café", "Chá", "Suco", "Refrigerante", "Água", "Vinho", "Cerveja", "Molho", "Ketchup", "Mostarda",
    "Maionese", "Vinagre", "Pimenta", "Orégano", "Manjericão", "Canela", "Chocolate Amargo", "Leite Condensado", "Creme De Leite", "Arroz Doce",
    //3. Profissões
    "Médico", "Enfermeiro", "Dentista", "Veterinário", "Farmacêutico", "Psicólogo", "Fisioterapeuta", "Nutricionista", "Terapeuta", "Socorrista",
    "Professor", "Educador", "Pedagogo", "Tutor", "Instrutor", "Pesquisador", "Cientista", "Historiador", "Geógrafo", "Filósofo",
    "Engenheiro", "Arquiteto", "Urbanista", "Designer", "Ilustrador", "Animador", "Programador", "Desenvolvedor", "Analista", "Técnico",
    "Eletricista", "Encanador", "Pedreiro", "Carpinteiro", "Marceneiro", "Pintor", "Soldador", "Mecânico", "Torneiro", "Operador",
    "Motorista", "Piloto", "Condutor", "Entregador", "Carteiro", "Caminhoneiro", "Taxista", "Navegador", "Comandante", "Capitão",
    "Advogado", "Juiz", "Promotor", "Delegado", "Perito", "Escrivão", "Defensor", "Procurador", "Notário", "Auditor",
    "Contador", "Economista", "Administrador", "Gestor", "Consultor", "Corretor", "Avaliador", "Bancário", "Tesoureiro", "Analista Financeiro",
    "Vendedor", "Atendente", "Caixa", "Balconista", "Recepcionista", "Comerciante", "Representante", "Negociador", "Distribuidor", "Comprador",
    "Cozinheiro", "Chef", "Padeiro", "Confeiteiro", "Açougueiro", "Peixeiro", "Merendeiro", "Garçom", "Bartender", "Sommelier",
    //4. Natureza
    "Árvore", "Floresta", "Mata", "Selva", "Bosque", "Campo", "Planície", "Montanha", "Serra", "Colina",
    "Vale", "Deserto", "Oásis", "Praia", "Costa", "Ilha", "Arquipélago", "Oceano", "Mar", "Lago",
    "Lagoa", "Rio", "Córrego", "Cachoeira", "Nascente", "Delta", "Estuário", "Pântano", "Brejo", "Mangue",
    "Neve", "Gelo", "Granizo", "Chuva", "Tempestade", "Vento", "Brisa", "Furacão", "Tornado", "Ciclone",
    "Nuvem", "Neblina", "Nevoeiro", "Orvalho", "Geada", "Sol", "Lua", "Estrela", "Planeta", "Cometa",
    "Asteroide", "Céu", "Horizonte", "Aurora", "Eclipse", "Vulcão", "Cratera", "Lava", "Rocha", "Pedra",
    "Areia", "Terra", "Solo", "Argila", "Mineral", "Cristal", "Quartzo", "Carvão", "Ferro", "Ouro",
    "Prata", "Cobre", "Planta", "Flor", "Folha", "Raiz", "Semente", "Tronco", "Galho", "Casca",
    "Musgo", "Alga", "Fungo", "Coral", "Recife", "Savanas", "Tundra", "Taiga", "Bioma", "Ecossistema",
    //5. Lugares
    "Cidade", "Vila", "Aldeia", "Bairro", "Rua", "Avenida", "Praça", "Parque", "Jardim", "Ponte",
    "Túnel", "Rodovia", "Estrada", "Cruzamento", "Rotatória", "Centro", "Subúrbio", "Distrito", "Capital", "Região",
    "País", "Estado", "Província", "Continente", "Mapa", "Fronteira", "Porto", "Aeroporto", "Estação", "Terminal",
    "Hospital", "Clínica", "Farmácia", "Escola", "Colégio", "Universidade", "Biblioteca", "Museu", "Teatro", "Cinema",
    "Igreja", "Templo", "Santuário", "Mosteiro", "Catedral", "Palácio", "Castelo", "Fortaleza", "Torre", "Monumento",
    "Hotel", "Pousada", "Albergue", "Restaurante", "Café", "Bar", "Mercado", "Feira", "Loja", "Shopping",
    "Fábrica", "Armazém", "Depósito", "Oficina", "Escritório", "Empresa", "Indústria", "Banco", "Correio", "Cartório",
    "Delegacia", "Quartel", "Tribunal", "Prefeitura", "Câmara", "Estádio", "Ginásio", "Arena", "Piscina", "Academia",
    "Zoológico", "Aquário", "Observatório", "Planetário", "Laboratório", "Cemitério", "Garagem", "Estacionamento", "Terminal Rodoviário", "Posto",
    //6. Animais
    "Abelha", "Águia", "Alce", "Aranha", "Baleia", "Borboleta", "Cachorro", "Camelo", "Canguru", "Cavalo",
    "Cobra", "Coelho", "Coruja", "Crocodilo", "Elefante", "Esquilo", "Falcão", "Galo", "Gato", "Girafa",
    "Golfinho", "Hamster", "Hipopótamo", "Jacaré", "Leão", "Leopardo", "Lobo", "Lontra", "Macaco", "Morcego",
    "Onça", "Ovelha", "Panda", "Papagaio", "Pato", "Pavão", "Peixe", "Pinguim", "Porco", "Rã",
    "Raposa", "Rato", "Rinoceronte", "Sapo", "Serpente", "Tartaruga", "Tigre", "Tubarão", "Urso", "Vaca",
    "Veado", "Zebra", "Caranguejo", "Estrela-do-mar", "Lagosta", "Polvo", "Água-viva", "Caracol", "Lagarto", "Iguana",
    "Formiga", "Besouro", "Joaninha", "Escorpião", "Arraia", "Enguia", "Atum", "Sardinha", "Gaivota", "Andorinha",
    "Corvo", "Pomba", "Cisne", "Ganso", "Galinha", "Peru", "Codorna", "Javali", "Texugo", "Doninha",
    "Foca", "Leão-marinho", "Morsa", "Antílope", "Búfalo", "Bisão", "Suricato", "Lêmure", "Orangotango", "Chimpanzé",
    //7. Elementos de fantasia
    "Dragão", "Fênix", "Unicórnio", "Grifo", "Quimera", "Hidra", "Kraken", "Gigante", "Anão", "Elfo",
    "Orc", "Goblin", "Troll", "Demônio", "Anjo", "Serafim", "Titã", "Espírito", "Fantasma", "Espectro",
    "Sombras", "Luz", "Trevas", "Magia", "Feitiço", "Encanto", "Maldição", "Runas", "Relíquia", "Artefato",
    "Amuleto", "Talismã", "Cajado", "Varinha", "Grimório", "Pergaminho", "Poção", "Elixir", "Cristal", "Obsidiana",
    "Mithril", "Adamantium", "Éter", "Mana", "Essência", "Energia", "Portal", "Dimensão", "Reino", "Império",
    "Trono", "Coroa", "Profecia", "Destino", "Caos", "Ordem", "Equilíbrio", "Abismo", "Vórtice", "Labirinto",
    "Torre", "Fortaleza", "Cidadela", "Templo", "Santuário", "Altar", "Relâmpago", "Chama", "Gelo", "Alquimia",
    "Varinha", "Fada", "Ogro", "Sangue", "Osso", "Escama", "Asa", "Garra", "Olho", "Máscara",
    "Espada", "Machado", "Arco", "Flecha", "Escudo", "Armadura", "Lâmina", "Martelo", "Orbe", "Sigilo",
    //8. Emoções
    "Alegria", "Tristeza", "Raiva", "Medo", "Nojo", "Surpresa", "Amor", "Ódio", "Esperança", "Desespero",
    "Ansiedade", "Calma", "Paz", "Tensão", "Orgulho", "Vergonha", "Culpa", "Alívio", "Euforia", "Melancolia",
    "Solidão", "Saudade", "Empatia", "Compaixão", "Inveja", "Ciúme", "Admiração", "Respeito", "Confiança", "Desconfiança",
    "Coragem", "Covardia", "Determinação", "Dúvida", "Fé", "Ceticismo", "Gratidão", "Frustração", "Satisfação", "Decepção",
    "Entusiasmo", "Apatia", "Curiosidade", "Tédio", "Interesse", "Fascínio", "Nostalgia", "Aceitação", "Rejeição", "Humilhação",
    "Arrependimento", "Remorso", "Prazer", "Dor", "Conforto", "Desconforto", "Admiração", "Temor", "Pânico", "Serenidade",
    "Timidez", "Otimismo", "Pessimismo", "Motivação", "Desânimo", "Carinho", "Afeto", "Ira", "Rancor", "Ressentimento",
    "Confusão", "Clareza", "Orgulho", "Vaidade", "Compreensão", "Tolerância", "Irritação", "Exaustão", "Alívio", "Encanto",
    //9. Partes do corpo
    "Cabeça", "Rosto", "Testa", "Sobrancelha", "Pálpebra", "Nariz", "Boca", "Lábio", "Dente", "Língua",
    "Mandíbula", "Queixo", "Bochecha", "Orelha", "Pescoço", "Nuca", "Garganta", "Clavícula", "Ombro", "Axila",
    "Braço", "Antebraço", "Cotovelo", "Pulso", "Mão", "Palma", "Dedo", "Unha", "Polegar", "Indicador",
    "Médio", "Anelar", "Mindinho", "Tórax", "Peito", "Costela", "Abdômen", "Barriga", "Umbigo", "Quadril",
    "Cintura", "Virilha", "Costas", "Lombar", "Coluna", "Escápula", "Pelve", "Glúteo", "Coxa", "Joelho",
    "Panturrilha", "Canela", "Tornozelo", "Calcanhar", "Pé", "Planta", "Dorso", "Dedão", "Articulação", "Cartilagem",
    "Músculo", "Tendão", "Ligamento", "Pele", "Poros", "Veia", "Artéria", "Pulmão", "Coração", "Estômago",
    "Fígado", "Rim", "Intestino", "Esôfago", "Traqueia", "Laringe", "Diafragma", "Pâncreas", "Baço", "Bexiga",
    "Cérebro", "Medula", "Nervo", "Glândula", "Hormônio", "Retina", "Íris", "Córnea", "Pupila", "Meninge",
    //10. Música e instrumentos musicais
    "Música", "Melodia", "Harmonia", "Ritmo", "Batida", "Tom", "Nota", "Acorde", "Escala", "Silêncio",
    "Som", "Eco", "Volume", "Vibração", "Letra", "Refrão", "Verso", "Canção", "Álbum", "Concerto",
    "Orquestra", "Banda", "Coral", "Maestro", "Cantor", "Cantora", "Compositor", "Intérprete", "Instrumentista", "Produtor",
    "Piano", "Teclado", "Órgão", "Violino", "Viola", "Violoncelo", "Contrabaixo", "Guitarra", "Violão", "Baixo",
    "Bateria", "Tambor", "Caixa", "Prato", "Xilofone", "Marimba", "Flauta", "Flautim", "Clarinete", "Oboé",
    "Saxofone", "Trompete", "Trombone", "Tuba", "Corneta", "Gaita", "Acordeão", "Sanfona", "Bandolim", "Cavaquinho",
    "Ukulele", "Harpa", "Lira", "Sitar", "Banjo", "Pandeiro", "Reco-reco", "Berimbau", "Atabaque", "Agogô",
    //11. Relações humanas
    "Amizade", "Inimizade", "Parceria", "Aliança", "Rivalidade", "Competição", "Cooperação", "Conflito", "Convívio", "Solidariedade",
    "Amor", "Paixão", "Carinho", "Afeto", "Apego", "Distanciamento", "Separação", "União", "Casamento", "Divórcio",
    "Família", "Parente", "Irmandade", "Paternidade", "Maternidade", "Filiação", "Tutela", "Adoção", "Cuidado", "Proteção",
    "Amante", "Casal", "Companheiro", "Companheira", "Parceiro", "Parceira", "Ex-namorado", "Ex-namorada", "Crush", "Pretendente",
    "Chefe", "Empregado", "Colega", "Sócio", "Cliente", "Fornecedor", "Líder", "Seguidor", "Mentor", "Aprendiz",
    "Aliado", "Inimigo", "Traidor", "Cúmplice", "Testemunha", "Estranho", "Conhecido", "Vizinho", "Convidado", "Anfitrião",
    //12. Tecnologia
    "Tecnologia", "Máquina", "Sistema", "Dispositivo", "Aparelho", "Equipamento", "Ferramenta", "Mecanismo", "Circuito", "Processador",
    "Computador", "Servidor", "Terminal", "Console", "Notebook", "Tablet", "Celular", "Smartphone", "Tela", "Monitor",
    "Teclado", "Mouse", "Sensor", "Câmera", "Microfone", "Alto-falante", "Fone", "Bateria", "Carregador", "Cabo",
    "Rede", "Internet", "Intranet", "Conexão", "Sinal", "Satélite", "Antena", "Nuvem", "Banco de dados", "Arquivo",
    "Software", "Aplicativo", "Programa", "Algoritmo", "Código", "Script", "Interface", "Plataforma", "Sistema operacional", "Atualização",
    "Firewall", "Criptografia", "Segurança", "Privacidade", "Vazamento", "Backup", "Automação", "Robô", "Inteligência artificial", "Simulação",
    //13. Conceitos abstratos, morais e filosóficos
    "Justiça", "Injustiça", "Verdade", "Mentira", "Bem", "Mal", "Ética", "Moral", "Virtude", "Pecado",
    "Liberdade", "Opressão", "Direito", "Dever", "Responsabilidade", "Culpa", "Inocência", "Condenação", "Perdão", "Redenção",
    "Vida", "Morte", "Nascimento", "Fim", "Começo", "Destino", "Acaso", "Escolha", "Consequência", "Sentido",
    "Existência", "Consciência", "Identidade", "Ego", "Alma", "Espírito", "Vontade", "Desejo", "Intenção", "Propósito",
    "Tempo", "Eternidade", "Infinito", "Vazio", "Nada", "Totalidade", "Caos", "Ordem", "Equilíbrio", "Ruptura",
    "Apocalipse", "Colapso", "Criação", "Destruição", "Renovação", "Esperança", "Desespero", "Medo", "Coragem", "Fé",
    //14. Ferramentas manuais
    "Martelo", "Marreta", "Malho", "Chave", "Chave inglesa", "Chave de fenda", "Chave Philips", "Alicate", "Alicate de corte", "Alicate de pressão",
    "Serrote", "Arco de serra", "Lima", "Formão", "Plaina", "Trena", "Nível", "Esquadro", "Compasso", "Régua",
    "Estilete", "Canivete", "Tesoura", "Grampo", "Sargento", "Morsa", "Punção", "Talhadeira", "Espátula", "Colher de pedreiro",
    "Pá", "Enxada", "Picareta", "Ancinho", "Foice", "Machado", "Marreta de borracha", "Escova de aço", "Lixa", "Raspador",
    //15. Máquinas
    "Máquina", "Motor", "Gerador", "Compressor", "Torno", "Fresadora", "Prensa", "Esteira", "Elevador", "Guindaste",
    "Escavadeira", "Retroescavadeira", "Trator", "Colheitadeira", "Betoneira", "Britadeira", "Perfuratriz", "Furadeira", "Parafusadeira", "Serra elétrica",
    "Serra circular", "Serra de fita", "Serra mármore", "Politriz", "Lixadeira", "Plainadeira", "Soldadora", "Inversora", "Transformador", "Painel elétrico",
    "Bomba", "Válvula", "Ventoinha", "Turbina", "Caldeira", "Reator", "Impressora 3D", "Robô industrial", "CNC", "Controlador",
    //16. Construções
    "Casa", "Prédio", "Edifício", "Apartamento", "Sobrado", "Galpão", "Armazém", "Fábrica", "Oficina", "Loja",
    "Escola", "Hospital", "Clínica", "Igreja", "Templo", "Catedral", "Capela", "Castelo", "Fortaleza", "Palácio",
    "Torre", "Ponte", "Viaduto", "Túnel", "Estrada", "Rodovia", "Barragem", "Dique", "Porto", "Aeroporto",
    "Estação", "Terminal", "Estádio", "Ginásio", "Arena", "Teatro", "Cinema", "Museu", "Biblioteca", "Shopping",
    "Mercado", "Feira", "Hotel", "Pousada", "Albergue", "Restaurante", "Bar", "Café", "Posto", "Garagem",
    //17. Cômodos
    "Sala", "Sala de estar", "Sala de jantar", "Quarto", "Dormitório", "Suíte", "Cozinha", "Copa", "Despensa", "Banheiro",
    "Lavabo", "Área de serviço", "Lavanderia", "Escritório", "Biblioteca", "Ateliê", "Estúdio", "Closet", "Corredor", "Hall",
    "Entrada", "Varanda", "Sacada", "Terraço", "Sótão", "Porão", "Adega", "Garagem", "Depósito", "Despacho",
    "Quarto infantil", "Quarto de hóspedes", "Sala de jogos", "Sala de reuniões", "Sala técnica", "Central", "Almoxarifado", "Arquivo", "Antessala", "Camarim",
    //18. Materiais de construção
    "Concreto", "Cimento", "Areia", "Brita", "Argamassa", "Cal", "Gesso", "Reboco", "Massa corrida", "Asfalto",
    "Tijolo", "Bloco", "Laje", "Viga", "Pilar", "Vergalhão", "Aço", "Ferro", "Alumínio", "Cobre",
    "Madeira", "Compensado", "MDF", "OSB", "Plástico", "PVC", "Vidro", "Fibra", "Borracha", "Isolante",
    "Telha", "Cerâmica", "Porcelanato", "Azulejo", "Granito", "Mármore", "Pedra", "Ardósia", "Quartzo", "Revestimento",
    "Tinta", "Verniz", "Selador", "Impermeabilizante", "Cola", "Adesivo", "Parafuso", "Prego", "Bucha", "Argola", "Resina",
    //19. Cores
    "Branco", "Preto", "Cinza", "Prata", "Dourado",
    "Vermelho", "Azul", "Verde", "Amarelo", "Laranja", "Roxo", "Rosa", "Marrom",
    "Bege", "Creme", "Vinho", "Bordô", "Turquesa", "Ciano", "Magenta",
    "Índigo", "Violeta", "Lilás", "Lavanda", "Oliva", "Musgo", "Esmeralda",
    "Safira", "Âmbar", "Caramelo", "Chocolate", "Areia", "Grafite",
    "Coral", "Pêssego", "Salmão", "Mostarda", "Ferrugem",
    "Azul claro", "Azul escuro", "Verde claro", "Verde escuro", "Cinza claro", "Cinza escuro",
    //20. Estados físicos
    "Sólido", "Líquido", "Gasoso", "Plasma",
    "Duro", "Macio", "Mole", "Rígido", "Flexível", "Elástico",
    "Frágil", "Resistente", "Quebrado", "Inteiro", "Danificado",
    "Liso", "Áspero", "Rugoso", "Poroso", "Polido",
    "Seco", "Molhado", "Úmido", "Encharcado",
    "Quente", "Frio", "Gelado", "Morno",
    "Pesado", "Leve", "Denso", "Oco", "Maciço",
    "Transparente", "Opaco", "Translúcido",
    "Aberto", "Fechado", "Trancado", "Destrancado",
    "Cheio", "Vazio", "Rachado", "Amassado", "Dobrado",
    "Estável", "Instável", "Fixo", "Móvel",
    "Novo", "Usado", "Velho", "Antigo", "Enferrujado",
    //21. Esportes e artigos esportivos
    "Futebol", "Basquete", "Vôlei", "Handebol", "Futsal", "Tênis", "Tênis de mesa", "Badminton", "Beisebol", "Softbol",
    "Rugby", "Críquete", "Hóquei", "Hóquei no gelo", "Hóquei em campo", "Golfe", "Polo", "Boliche", "Bocha", "Peteca",
    "Natação", "Mergulho", "Polo aquático", "Surf", "Windsurf", "Kitesurf", "Skate", "Patins", "Ciclismo", "Mountain bike",
    "Atletismo", "Corrida", "Maratona", "Salto", "Arremesso", "Lançamento",
    "Boxe", "Judô", "Caratê", "Taekwondo", "Jiu-jitsu", "Esgrima", "Luta livre", "Muay thai",
    "Escalada", "Alpinismo", "Esqui", "Snowboard",
    "Bola", "Bola de futebol", "Bola de basquete", "Raquete", "Raquete de tênis", "Raquete de pingue-pongue",
    "Taco", "Bastão", "Luva", "Capacete", "Caneleira", "Joelheira", "Cotoveleira",
    "Rede", "Trave", "Cesta", "Alvo", "Pista", "Quadra", "Campo",
    //22. Hobbies
    "Leitura", "Escrita", "Desenho", "Pintura", "Ilustração", "Escultura", "Grafite",
    "Fotografia", "Filmagem", "Edição", "Animação",
    "Música", "Canto", "Composição", "Instrumento", "Violão", "Guitarra", "Piano", "Teclado", "Bateria",
    "Jogos", "Videogame", "Tabuleiro", "Cartas", "RPG", "Quebra-cabeça",
    "Programação", "Codificação", "Modelagem", "Impressão 3D",
    "Artesanato", "Crochê", "Tricô", "Costura", "Bordado", "Marcenaria", "Cerâmica",
    "Culinária", "Confeitaria", "Panificação",
    "Jardinagem", "Horticultura", "Cultivo",
    "Observação", "Astronomia", "Telescópio",
    "Colecionismo", "Miniaturas", "Selos", "Moedas", "Cartas",
    "Origami", "Caligrafia", "Xadrez", "Damas", "Sudoku",
    "Meditação", "Yoga", "Caminhada", "Trilha", "Camping",
    //23. Meios de transporte
    "Carro", "Automóvel", "Caminhão", "Caminhonete", "Ônibus", "Micro-ônibus", "Van",
    "Moto", "Motocicleta", "Scooter", "Bicicleta", "Triciclo", "Quadriciclo",
    "Trem", "Metrô", "Vagão", "Locomotiva", "Bonde", "Monotrilho",
    "Avião", "Jato", "Hidroavião", "Planador", "Helicóptero", "Dirigível",
    "Navio", "Barco", "Lancha", "Iate", "Balsa", "Canoa", "Caiaque", "Submarino",
    "Navio cargueiro", "Navio petroleiro", "Porta-aviões",
    "Patinete", "Hoverboard",
    "Carro elétrico", "Carro híbrido",
    "Trenó", "Teleférico", "Funicular",
    "Carroça", "Charrete",
    "Espaçonave", "Foguete", "Ônibus espacial",
    "Balão",
    //24. Vestuário
    "Camiseta", "Blusa", "Regata", "Suéter", "Pulôver",
    "Vestido", "Saia", "Shorts", "Bermuda", "Macacão",
    "Terno", "Blazer", "Colete", "Sobretudo", "Poncho",
    "Pijama", "Roupão", "Uniforme",
    "Roupa íntima", "Cueca", "Calcinha", "Sutiã",
    "Meia-calça", "Legging",
    "Biquíni", "Maiô", "Sunga",
    "Tênis", "Bota", "Chinelo", "Sandália", "Sapatilha", "Coturno",
    "Luvas", "Cachecol", "Lenço", "Gravata", "Laço",
    "Pulseira", "Colar", "Anel", "Brinco",
    "Capuz", "Touca",
    "Avental", "Farda", "Fantasia",
    // 25. Países (Geografia é excelente para Jinx)
    "Afeganistão", "África do Sul", "Albânia", "Alemanha", "Andorra", "Angola", "Arábia Saudita", "Argélia", "Argentina", "Armênia",
    "Austrália", "Áustria", "Azerbaijão", "Bahamas", "Bangladesh", "Barbados", "Bahrein", "Bélgica", "Belize", "Benin",
    "Bielorrússia", "Bolívia", "Bósnia", "Botsuana", "Brasil", "Brunei", "Bulgária", "Burkina Faso", "Burundi", "Butão",
    "Cabo Verde", "Camarões", "Camboja", "Canadá", "Catar", "Cazaquistão", "Chade", "Chile", "China", "Chipre",
    "Colômbia", "Comores", "Congo", "Coreia do Norte", "Coreia do Sul", "Costa do Marfim", "Costa Rica", "Croácia", "Cuba", "Dinamarca",
    "Djibouti", "Dominica", "Egito", "El Salvador", "Emirados Árabes", "Equador", "Eritreia", "Eslováquia", "Eslovênia", "Espanha",
    "Estados Unidos", "Estônia", "Etiópia", "Fiji", "Filipinas", "Finlândia", "França", "Gabão", "Gâmbia", "Gana",
    "Geórgia", "Granada", "Grécia", "Guatemala", "Guiana", "Guiné", "Haiti", "Holanda", "Honduras", "Hungria",
    "Iêmen", "Índia", "Indonésia", "Irã", "Iraque", "Irlanda", "Islândia", "Israel", "Itália", "Jamaica",
    "Japão", "Jordânia", "Kuwait", "Laos", "Lesoto", "Letônia", "Líbano", "Libéria", "Líbia", "Liechtenstein",
    "Lituânia", "Luxemburgo", "Macedônia", "Madagascar", "Malásia", "Malaui", "Maldivas", "Mali", "Malta", "Marrocos",
    "Maurício", "Mauritânia", "México", "Mianmar", "Moçambique", "Moldávia", "Mônaco", "Mongólia", "Montenegro", "Namíbia",
    "Nepal", "Nicarágua", "Níger", "Nigéria", "Noruega", "Nova Zelândia", "Omã", "Panamá", "Papua Nova Guiné", "Paquistão",
    "Paraguai", "Peru", "Polônia", "Portugal", "Quênia", "Quirguistão", "Reino Unido", "República Checa", "Romênia", "Ruanda",
    "Rússia", "Samoa", "San Marino", "Santa Lúcia", "São Tomé e Príncipe", "Senegal", "Serra Leoa", "Sérvia", "Singapura", "Síria",
    "Somália", "Sri Lanka", "Suazilândia", "Sudão", "Suécia", "Suíça", "Suriname", "Tailândia", "Taiwan", "Tajiquistão",
    "Tanzânia", "Timor-Leste", "Togo", "Tonga", "Trinidad e Tobago", "Tunísia", "Turcomenistão", "Turquia", "Tuvalu", "Ucrânia",
    "Uganda", "Uruguai", "Uzbequistão", "Vanuatu", "Vaticano", "Venezuela", "Vietnã", "Zâmbia", "Zimbábue",
    // 26. Capitais e Cidades Importantes (Mundo + Brasil)
    "Brasília", "São Paulo", "Rio de Janeiro", "Salvador", "Belo Horizonte", "Curitiba", "Manaus", "Recife", "Porto Alegre", "Fortaleza",
    "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís", "Maceió", "Natal", "Campo Grande", "Teresina", "João Pessoa",
    "Aracaju", "Cuiabá", "Porto Velho", "Florianópolis", "Macapá", "Rio Branco", "Vitória", "Boa Vista", "Palmas", "Santos",
    "Tóquio", "Nova York", "Paris", "Londres", "Berlim", "Roma", "Madri", "Pequim", "Moscou", "Washington",
    "Buenos Aires", "Lisboa", "Ottawa", "Camberra", "Seul", "Bangkok", "Cairo", "Atenas", "Amsterdã", "Bruxelas",
    "Viena", "Estocolmo", "Oslo", "Copenhague", "Helsinque", "Dublin", "Berna", "Varsóvia", "Praga", "Budapeste",
    "Kiev", "Istambul", "Jerusalém", "Dubai", "Teerã", "Bagdá", "Délhi", "Mumbai", "Jacarta", "Manila",
    "Hanoi", "Kuala Lumpur", "Cingapura", "Taipei", "Hong Kong", "Xangai", "Sydney", "Melbourne", "Auckland", "Cabo",
    "Joanesburgo", "Nairóbi", "Lagos", "Cairo", "Casablanca", "Bogotá", "Lima", "Santiago", "Caracas", "Quito",
    "La Paz", "Assunção", "Montevidéu", "Havana", "Los Angeles", "Chicago", "Miami", "Las Vegas", "São Francisco",
    // 27. Marcas Famosas (Gera muito match fácil)
    "Google", "Apple", "Microsoft", "Amazon", "Facebook", "Coca-Cola", "Pepsi", "McDonald's", "Burger King", "Nike",
    "Adidas", "Puma", "Samsung", "Sony", "Nintendo", "PlayStation", "Xbox", "Netflix", "Disney", "Marvel",
    "DC", "Toyota", "Honda", "Ford", "Chevrolet", "Volkswagen", "Fiat", "Ferrari", "Lamborghini", "Porsche",
    "BMW", "Mercedes", "Audi", "Tesla", "Uber", "Instagram", "Twitter", "TikTok", "YouTube", "Spotify",
    "Visa", "Mastercard", "Nubank", "Itaú", "Bradesco", "Caixa", "Banco do Brasil", "Nestlé", "Garoto", "Lacta",
    "Sadia", "Perdigão", "Seara", "Omo", "Veja", "Bombril", "Colgate", "Oral-B", "Dove", "Nivea",
    "Avon", "Natura", "Boticário", "Zara", "Renner", "Riachuelo", "C&A", "Hering", "Havaianas", "Melissa",
    "Rolex", "Gucci", "Prada", "Louis Vuitton", "Chanel", "Dior", "Versace", "Armani", "Calvin Klein", "Tommy Hilfiger",
    "Lego", "Barbie", "Hot Wheels", "Monopoly", "Uno", "Canon", "Nikon", "GoPro", "Dell", "HP",
    "Intel", "AMD", "Nvidia", "Asus", "Acer", "Lenovo", "Motorola", "Xiaomi", "LG", "Panasonic",
    // 28. Personagens de Ficção (Pop Culture)
    "Batman", "Superman", "Homem-Aranha", "Hulk", "Thor", "Homem de Ferro", "Capitão América", "Mulher Maravilha", "Flash", "Aquaman",
    "Coringa", "Thanos", "Darth Vader", "Luke Skywalker", "Yoda", "Obi-Wan", "Harry Potter", "Hermione", "Rony", "Voldemort",
    "Dumbledore", "Gandalf", "Frodo", "Gollum", "Aragorn", "Legolas", "Sauron", "Sherlock Holmes", "Watson", "James Bond",
    "Tarzan", "Mogli", "Drácula", "Frankenstein", "Lobisomem", "Papai Noel", "Coelhinho da Páscoa", "Fada do Dente", "Mickey", "Minnie",
    "Pato Donald", "Pateta", "Pluto", "Pica-Pau", "Tom", "Jerry", "Scooby-Doo", "Salsicha", "Fred", "Barney",
    "Bob Esponja", "Patrick", "Lula Molusco", "Homer Simpson", "Marge", "Bart", "Lisa", "Goku", "Vegeta", "Naruto",
    "Sasuke", "Luffy", "Pikachu", "Ash", "Mario", "Luigi", "Peach", "Bowser", "Sonic", "Tails",
    "Link", "Zelda", "Kratos", "Master Chief", "Pac-Man", "Ryu", "Ken", "Chun-Li", "Sub-Zero", "Scorpion",
    // 29. Zodíaco e Esoterismo
    "Áries", "Touro", "Gêmeos", "Câncer", "Leão", "Virgem", "Libra", "Escorpião", "Sagitário", "Capricórnio",
    "Aquário", "Peixes", "Horóscopo", "Mapa Astral", "Ascendente", "Lua", "Sol", "Tarô", "Carta", "Vidente",
    "Bola de Cristal", "Incensos", "Cristais", "Energia", "Chakra", "Aura", "Karma", "Dharma", "Reencarnação", "Espiritismo",
    // 30. Bebidas (Expandindo)
    "Vodka", "Whisky", "Gin", "Rum", "Tequila", "Conhaque", "Licor", "Saquê", "Champanhe", "Espumante",
    "Cachaça", "Caipirinha", "Batida", "Coquetel", "Martini", "Margarita", "Mojito", "Piña Colada", "Cosmopolitan", "Negroni",
    "Chopp", "IPA", "Lager", "Pilsen", "Stout", "Weiss", "Cidra", "Hidromel", "Grogue", "Absinto",
    "Água com gás", "Água de coco", "Caldo de cana", "Garapa", "Chimarrão", "Tereré", "Mate", "Cappuccino", "Expresso", "Mocaccino",
    // 31. Vestuário (Expandindo Tecidos e Acessórios)
    "Algodão", "Lã", "Seda", "Linho", "Veludo", "Jeans", "Couro", "Nylon", "Poliéster", "Cetim",
    "Renda", "Malha", "Moletom", "Camurça", "Flanela", "Viscose", "Elastano", "Microfibra", "Sarja", "Tule",
    "Zíper", "Botão", "Bolso", "Gola", "Manga", "Barra", "Costura", "Decote", "Fivela", "Cadarço",
    "Salto Alto", "Plataforma", "Sola", "Palmilha", "Bolsa de Mão", "Mochila", "Pochete", "Carteira", "Mala", "Necessaire",
    // 32. Doenças e Saúde (Termos comuns)
    "Gripe", "Resfriado", "Febre", "Tosse", "Dor de cabeça", "Enxaqueca", "Alergia", "Asma", "Bronquite", "Pneumonia",
    "Diabetes", "Hipertensão", "Colesterol", "Gastrite", "Úlcera", "Cárie", "Gengivite", "Fratura", "Torção", "Luxação",
    "Corte", "Ferida", "Cicatriz", "Hematoma", "Inflamação", "Infecção", "Vírus", "Bactéria", "Vacina", "Injeção",
    "Comprimido", "Xarope", "Pomada", "Curativo", "Gesso", "Muleta", "Cadeira de rodas", "Óculos", "Lente", "Aparelho",
    // 33. Elementos Químicos e Ciência
    "Hidrogênio", "Hélio", "Lítio", "Berílio", "Boro", "Carbono", "Nitrogênio", "Oxigênio", "Flúor", "Neon",
    "Sódio", "Magnésio", "Alumínio", "Silício", "Fósforo", "Enxofre", "Cloro", "Argônio", "Potássio", "Cálcio",
    "Ferro", "Cobre", "Zinco", "Prata", "Ouro", "Mercúrio", "Chumbo", "Urânio", "Plutônio", "Titânio",
    "Átomo", "Molécula", "Elétron", "Próton", "Nêutron", "Célula", "DNA", "RNA", "Genética", "Evolução",
    "Gravidade", "Relatividade", "Física", "Química", "Biologia", "Matemática", "Cálculo", "Álgebra", "Geometria", "Estatística",
    // 34. Jogos e Baralho
    "Ás", "Rei", "Dama", "Valete", "Coringa", "Espadas", "Copas", "Ouros", "Paus", "Naip",
    "Truco", "Pôquer", "Buraco", "Paciência", "Cacheta", "Dominó", "Dama", "Xadrez", "Gamão", "Ludo",
    "Dado", "Tabuleiro", "Peça", "Ficha", "Jogador", "Vencedor", "Perdedor", "Empate", "Rodada", "Turno",
    // 35. Ferramentas Digitais e Internet
    "Site", "Blog", "Link", "URL", "Email", "Spam", "Vírus", "Hacker", "Senha", "Login",
    "Emoji", "Sticker", "Gif", "Meme", "Viral", "Trend", "Hashtag", "Post", "Story", "Reels",
    "Like", "Comentário", "Compartilhamento", "Seguidor", "Influencer", "Youtuber", "Streamer", "Gamer", "Noob", "Pro",
    "Download", "Upload", "Streaming", "Wi-Fi", "Bluetooth", "USB", "HDMI", "Pixel", "Resolução", "Gigabyte",
    // 36. Eventos e Festas
    "Aniversário", "Casamento", "Noivado", "Batizado", "Formatura", "Churrasco", "Festa", "Balada", "Show", "Festival",
    "Carnaval", "Páscoa", "Natal", "Ano Novo", "Réveillon", "São João", "Festa Junina", "Halloween", "Dia das Mães", "Dia dos Pais",
    "Dia dos Namorados", "Feriado", "Férias", "Viagem", "Piquenique", "Luau", "Rave", "Concerto", "Exposição", "Feira",
    // 37. Veículos (Expandido)
    "Ambulância", "Viatura", "Bombeiro", "Guincho", "Trator", "Empilhadeira", "Betoneira", "Tanque", "Jipe", "Limusine",
    "Conversível", "Picape", "Perua", "Hatch", "Sedã", "SUV", "Crossover", "Minivan", "Utilitário", "Esportivo",
    "Balsa", "Lancha", "Iate", "Veleiro", "Escuna", "Transatlântico", "Porta-aviões", "Submarino", "Caiaque", "Canoa",
    "Jato", "Biplano", "Monomotor", "Bimotor", "Planador", "Asa-delta", "Parapente", "Paraquedas", "Balão", "Dirigível",
    // 38. Adjetivos Simples (Que funcionam como "Estado")
    // Cuidado com estes, use apenas se quiser permitir qualidades
    "Rápido", "Lento", "Forte", "Fraco", "Grande", "Pequeno", "Alto", "Baixo", "Gordo", "Magro",
    "Bonito", "Feio", "Limpo", "Sujo", "Claro", "Escuro", "Cheio", "Vazio", "Novo", "Velho",
    "Jovem", "Idoso", "Rico", "Pobre", "Feliz", "Triste", "Doente", "Saudável", "Vivo", "Morto",
    "Quente", "Frio", "Seco", "Molhado", "Doce", "Salgado", "Azedo", "Amargo", "Picante", "Insosso",
    // 39. Coisas de Escritório
    "Grampeador", "Grampo", "Clips", "Perfurador", "Pasta", "Arquivo", "Envelope", "Etiqueta", "Carimbo", "Tinteiro",
    "Crachá", "Cordão", "Lousa", "Quadro Branco", "Apagador", "Giz", "Canetão", "Projetor", "Slide", "Relatório",
    "Planilha", "Documento", "Contrato", "Nota Fiscal", "Recibo", "Boleto", "Cheque", "Dinheiro", "Moeda", "Cofre",
    // 40. Figuras Históricas e Famosos (Gera muito match!)
    "Albert Einstein", "Isaac Newton", "Leonardo da Vinci", "Michelangelo", "Picasso", "Van Gogh", "Salvador Dalí", "Beethoven", "Mozart", "Bach",
    "Shakespeare", "Homero", "Dante Alighieri", "Machado de Assis", "Clarice Lispector", "Fernando Pessoa", "Carlos Drummond", "Monteiro Lobato", "Paulo Coelho", "Jorge Amado",
    "Cleópatra", "Júlio César", "Alexandre o Grande", "Napoleão", "Joana d'Arc", "Rei Arthur", "Rainha Elizabeth", "Princesa Diana", "Gengis Khan", "Nelson Mandela",
    "Gandhi", "Martin Luther King", "Madre Teresa", "Papa Francisco", "Jesus", "Buda", "Maomé", "Moisés", "Noé", "Dalai Lama",
    "Elvis Presley", "Michael Jackson", "Madonna", "Beyoncé", "Lady Gaga", "Rihanna", "Shakira", "Anitta", "Ivete Sangalo", "Roberto Carlos",
    "Pelé", "Maradona", "Messi", "Cristiano Ronaldo", "Neymar", "Senna", "Schumacher", "Hamilton", "Tyson", "Ali",
    "Marilyn Monroe", "Audrey Hepburn", "Charlie Chaplin", "Walt Disney", "Steven Spielberg", "Tarantino", "Scorsese", "Hitchcock", "Stan Lee", "J.K. Rowling",
    "Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk", "Jeff Bezos", "Warren Buffett", "Silvio Santos", "Faustão", "Xuxa", "Gugu",
    "Lula", "Bolsonaro", "Obama", "Trump", "Biden", "Putin", "Fidel Castro", "Che Guevara", "Lenin", "Stalin",
    "Hitler", "Mussolini", "Churchill", "Roosevelt", "Kennedy", "Lincoln", "Washington", "Pedro Álvares Cabral", "Dom Pedro", "Tiradentes",
    // 41. Times de Futebol (Brasil e Mundo)
    "Flamengo", "Corinthians", "Palmeiras", "São Paulo", "Vasco", "Santos", "Grêmio", "Internacional", "Cruzeiro", "Atlético Mineiro",
    "Botafogo", "Fluminense", "Bahia", "Vitória", "Sport", "Santa Cruz", "Náutico", "Fortaleza", "Ceará", "Coritiba",
    "Athletico Paranaense", "Chapecoense", "Avaí", "Figueirense", "Goiás", "Vila Nova", "Paysandu", "Remo", "Ponte Preta", "Guarani",
    "Real Madrid", "Barcelona", "Atlético de Madrid", "Sevilla", "Valencia", "Manchester United", "Manchester City", "Liverpool", "Chelsea", "Arsenal",
    "Tottenham", "Juventus", "Milan", "Inter de Milão", "Roma", "Napoli", "Bayern de Munique", "Borussia Dortmund", "PSG", "Lyon",
    "Marseille", "Porto", "Benfica", "Sporting", "Ajax", "PSV", "Boca Juniors", "River Plate", "Peñarol", "Nacional",
    "Seleção Brasileira", "Seleção Argentina", "Seleção Alemã", "Seleção Italiana", "Seleção Francesa", "Copa do Mundo", "Champions League", "Libertadores", "Brasileirão", "Estadual",
    // 42. Outros Esportes (Times e Termos)
    "Lakers", "Bulls", "Warriors", "Celtics", "Heat", "Knicks", "Patriots", "Cowboys", "Packers", "Giants",
    "Yankees", "Red Sox", "Dodgers", "Ferrari", "McLaren", "Mercedes", "Red Bull", "Williams", "Renault", "Haas",
    "UFC", "MMA", "Octógono", "Nocaute", "Finalização", "Cinturão", "Tatame", "Quimono", "Faixa Preta", "Dojô",
    "Touchdown", "Quarterback", "Dunk", "Ace", "Match Point", "Tie-break", "Set", "Game", "Pit Stop", "Pole Position",
    // 43. Raças de Cães e Gatos
    "Vira-lata", "Poodle", "Labrador", "Golden Retriever", "Bulldog", "Pug", "Pastor Alemão", "Rottweiler", "Pitbull", "Pinscher",
    "Yorkshire", "Shih Tzu", "Maltês", "Chihuahua", "Beagle", "Dálmata", "Husky Siberiano", "São Bernardo", "Doberman", "Boxer",
    "Cocker Spaniel", "Dachshund", "Salsicha", "Chow Chow", "Akita", "Border Collie", "Lulu da Pomerânia", "Basset", "Greyhound", "Mastiff",
    "Siamês", "Persa", "Angorá", "Maine Coon", "Sphynx", "Ragdoll", "Bengal", "Himalaia", "Bombaim", "Gato Preto",
    // 44. Flores e Plantas (Específicas)
    "Rosa", "Tulipa", "Orquídea", "Margarida", "Girassol", "Lírio", "Violeta", "Cravo", "Jasmim", "Hortênsia",
    "Bromélia", "Cacto", "Suculenta", "Samambaia", "Bambu", "Bonsai", "Eucalipto", "Pinheiro", "Ipê", "Pau-Brasil",
    "Babosa", "Camomila", "Hortelã", "Alecrim", "Coentro", "Salsa", "Cebolinha", "Arruda", "Manjerona", "Sálvia",
    "Vitória-régia", "Flor de Lótus", "Dente-de-leão", "Lavanda", "Hibisco", "Azaleia", "Begônia", "Copo-de-leite", "Gérbera", "Petúnia",
    // 45. Gêneros Musicais e Danças
    "Rock", "Pop", "Samba", "Pagode", "Sertanejo", "Funk", "Forró", "Axé", "MPB", "Bossa Nova",
    "Jazz", "Blues", "Soul", "R&B", "Hip Hop", "Rap", "Trap", "Reggae", "Eletrônica", "House",
    "Techno", "Trance", "Gospel", "Clássica", "Ópera", "Country", "Folk", "Indie", "K-Pop", "Latina",
    "Reggaeton", "Salsa", "Tango", "Valsa", "Bolero", "Zumba", "Ballet", "Sapateado", "Dança do Ventre", "Flamenco",
    // 46. Gêneros de Filmes e Termos de Cinema
    "Comédia", "Drama", "Terror", "Suspense", "Ação", "Aventura", "Romance", "Ficção Científica", "Documentário", "Animação",
    "Musical", "Faroeste", "Policial", "Guerra", "Fantasia", "Herói", "Tragédia", "Sátira", "Curta-metragem", "Longa-metragem",
    "Oscar", "Globo de Ouro", "Emmy", "Grammy", "Palma de Ouro", "Diretor", "Ator", "Atriz", "Dublê", "Roteiro",
    "Pipoca", "Ingresso", "Bilheteria", "Estreia", "Trailer", "Spoiler", "Cena", "Câmera", "Luz", "Ação",
    // 47. Mitologia e Religião (Deuses e Seres)
    "Zeus", "Hera", "Poseidon", "Ades", "Atena", "Apolo", "Ártemis", "Ares", "Afrodite", "Hermes",
    "Thor", "Odin", "Loki", "Freya", "Hela", "Hércules", "Medusa", "Minotauro", "Centauro", "Pégaso",
    "Sereia", "Ciclope", "Fênix", "Leviatã", "Belzebu", "Lúcifer", "Satanás", "Querubim", "Arcanjo", "Santo",
    "Bíblia", "Alcorão", "Torá", "Vedas", "Igreja", "Mesquita", "Sinagoga", "Terreiro", "Altar", "Rosário",
    // 48. Moedas e Economia
    "Real", "Dólar", "Euro", "Libra", "Iene", "Peso", "Rublo", "Franco", "Yuan", "Rúpia",
    "Bitcoin", "Ethereum", "Criptomoeda", "Pix", "Cartão", "Crédito", "Débito", "Juros", "Inflação", "Imposto",
    "Salário", "Aposentadoria", "Bolsa de Valores", "Ação", "Investimento", "Poupança", "Tesouro", "Dívida", "Empréstimo", "Financiamento",
    // 49. Pedras Preciosas e Metais
    "Diamante", "Rubi", "Esmeralda", "Safira", "Ametista", "Topázio", "Turquesa", "Pérola", "Opala", "Ônix",
    "Jade", "Água-marinha", "Cristal", "Quartzo", "Granada", "Ágata", "Malaquita", "Obsidiana", "Lápis-lazúli", "Citrino",
    "Ouro Branco", "Ouro Rosé", "Platina", "Titânio", "Bronze", "Latão", "Estanho", "Níquel", "Chumbo", "Mercúrio",
    // 50. Anatomia Específica (Mais detalhada)
    "Cílios", "Retina", "Tímpano", "Lóbulo", "Narina", "Septo", "Gengiva", "Canino", "Molar", "Siso",
    "Amígdala", "Tireoide", "Aorta", "Ventrículo", "Glóbulo", "Plaqueta", "Plasma", "Bílis", "Apêndice", "Cóccix",
    "Fêmur", "Tíbia", "Fíbula", "Rádio", "Ulna", "Úmero", "Esterno", "Bacia", "Menisco", "Tendão de Aquiles",
    "Neurônio", "Sinapse", "Derme", "Epiderme", "Folículo", "Vesícula", "Próstata", "Útero", "Ovário", "Trompa",
    // 51. Coisas de Casa (Específicos de Cozinha/Limpeza)
    "Liquidificador", "Batedeira", "Torradeira", "Sanduicheira", "Airfryer", "Cafeteira", "Chaleira", "Mixer", "Processador", "Espremedor",
    "Panela de Pressão", "Frigideira", "Wok", "Caçarola", "Leiteira", "Escorredor", "Ralo", "Sifão", "Torneira", "Filtro",
    "Vassoura", "Rodo", "Pá", "MOP", "Aspirador", "Robô Aspirador", "Espanador", "Pano", "Flanela", "Esponja",
    "Detergente", "Sabão em Pó", "Amaciante", "Água Sanitária", "Desinfetante", "Multiuso", "Lustra-móveis", "Inseticida", "Naftalina", "Aromatizador",
    // 52. Papelaria e Escritório (Expandido)
    "Caderno", "Agenda", "Planner", "Bloco", "Post-it", "Fichário", "Pasta Suspensa", "Arquivo Morto", "Envelope", "Etiqueta",
    "Caneta Azul", "Caneta Vermelha", "Caneta Preta", "Lapiseira", "Grafite", "Marca-texto", "Corretivo", "Cola Bastão", "Cola Branca", "Durex",
    "Fita Crepe", "Fita Isolante", "Dupla Face", "Estilete", "Tesoura", "Grampeador", "Extrator", "Perfurador", "Carimbo", "Almofada",
    "Calculadora", "Régua", "Compasso", "Transferidor", "Esquadro", "Gabarito", "Prancheta", "Lousa", "Giz", "Apagador",
    // 53. Sobremesas e Doces Brasileiros
    "Brigadeiro", "Beijinho", "Cajuzinho", "Doce de Leite", "Pé de Moleque", "Paçoca", "Rapadura", "Cocada", "Quindim", "Bolo de Rolo",
    "Goiabada", "Romeu e Julieta", "Pudim", "Manjar", "Sagu", "Canjica", "Pamonha", "Curau", "Arroz Doce", "Maria Mole",
    "Suspiro", "Churros", "Sonho", "Carolina", "Bomba", "Eclair", "Trufa", "Bombom", "Barra de Chocolate", "Ovo de Páscoa",
    "Panetone", "Chocotone", "Rabanada", "Pavê", "Mousse", "Gelatina", "Salada de Frutas", "Açaí", "Cupuaçu", "Tapioca",
    // 54. Jogos de Tabuleiro e Brinquedos
    "Banco Imobiliário", "War", "Imagem e Ação", "Detetive", "Jogo da Vida", "Cara a Cara", "Perfil", "Quest", "Uno", "Pife",
    "Dominó", "Dama", "Xadrez", "Gamão", "Ludo", "Trilha", "Resta Um", "Cubo Mágico", "Quebra-cabeça", "Memória",
    "Bola de Gude", "Pião", "Ioiô", "Pipa", "Estilingue", "Bila", "Peteca", "Amarelinha", "Corda", "Elástico",
    "Boneca", "Carrinho", "Autorama", "Ferrorama", "Lego", "Playmobil", "Massinha", "Slime", "Skate", "Patins",
    // 55. Sentimentos e Adjetivos de Personalidade (Profundos)
    "Teimoso", "Gentil", "Egoísta", "Altruísta", "Tímido", "Extrovertido", "Introvertido", "Sincero", "Falso", "Leal",
    "Traidor", "Corajoso", "Medroso", "Ansioso", "Calmo", "Estressado", "Nervoso", "Feliz", "Deprimido", "Eufórico",
    "Inteligente", "Sábio", "Ignorante", "Burro", "Esperto", "Ingênuo", "Malicioso", "Bondoso", "Maldoso", "Cruel",
    "Generoso", "Avarento", "Pão-duro", "Gastão", "Organizado", "Bagunçado", "Preguiçoso", "Proativo", "Criativo", "Racional",
    // 56. Phobias e Medos (Comuns)
    "Aracnofobia", "Claustrofobia", "Acrofobia", "Agorafobia", "Tripofobia", "Fobia Social", "Medo de Altura", "Medo de Escuro", "Medo de Palhaço", "Medo de Avião",
    "Pânico", "Susto", "Pesadelo", "Assombração", "Fantasma", "Vulto", "Espírito", "Monstro", "Bicho-papão", "Homem do Saco",
    // 57. Universo Geek e RPG
    "Mago", "Guerreiro", "Ladino", "Clérigo", "Paladino", "Bárbaro", "Druida", "Ranger", "Bardo", "Monge",
    "Feiticeiro", "Necromante", "Vampiro", "Lobisomem", "Zumbi", "Esqueleto", "Múmia", "Fantasma", "Lich", "Dragão",
    "Dungeon", "Masmorra", "Castelo", "Taverna", "Vila", "Reino", "Império", "Floresta", "Pântano", "Montanha",
    "Espada", "Escudo", "Arco", "Flecha", "Machado", "Martelo", "Cajado", "Varinha", "Adaga", "Poção",
    // 58. Cores Específicas (Expandido)
    "Carmesim", "Escarlate", "Bordô", "Ocre", "Cáqui", "Salmão", "Coral", "Pêssego", "Ciano", "Turquesa",
    "Anil", "Índigo", "Violeta", "Lavanda", "Lilás", "Magenta", "Fúcsia", "Rosa Choque",
    "Oliva", "Verde Água", "Azul Bebê", "Azul Marinho", "Azul Royal", "Cinza Chumbo", "Prata", "Dourado", "Bronze", "Cobre",
    // 59. Material Escolar e Artes
    "Pincel", "Tinta", "Aquarela", "Guache", "Óleo", "Acrílica", "Tela", "Cavalete", "Paleta", "Argila",
    "Carvão", "Giz de Cera", "Lápis de Cor", "Canetinha", "Hidrocor", "Papel", "Cartolina", "Papel Pardo", "Papel Manteiga", "Papel Alumínio",
    "Sulfite", "Papel Canson", "Papel Crepom", "Papel de Seda", "Origami", "Dobradura", "Recorte", "Colagem", "Mosaico", "Escultura",
    // 60. Fenômenos Naturais e Clima
    "Furacão", "Tornado", "Ciclone", "Tufão", "Terremoto", "Maremoto", "Tsunami", "Erupção", "Avalanche", "Deslizamento",
    "Inundação", "Enchente", "Seca", "Estiagem", "Geada", "Nevasca", "Granizo", "Raio", "Trovão", "Relâmpago",
    "Arco-íris", "Aurora Boreal", "Eclipse", "Sol da Meia Noite", "Estrela Cadente", "Meteoro", "Cratera", "Buraco Negro", "Supernova", "Big Bang",
    // 61. Família e Parentesco (Completo)
    "Mãe", "Pai", "Filho", "Filha", "Irmão", "Irmã", "Avô", "Avó", "Neto", "Neta",
    "Bisavô", "Bisavó", "Bisneto", "Bisneta", "Tio", "Tia", "Sobrinho", "Sobrinha", "Primo", "Prima",
    "Sogro", "Sogra", "Genro", "Nora", "Cunhado", "Cunhada", "Padrasto", "Madrasta", "Enteado", "Enteada",
    "Padrinho", "Madrinha", "Afilhado", "Afilhada", "Compadre", "Comadre", "Marido", "Esposa", "Noivo", "Noiva",
    // 62. Palavras Aleatórias "Difíceis" (Ótimas para desempatar)
    "Paralelepípedo", "Otorrinolaringologista", "Inconstitucionalissimamente", "Oftalmologista", "Caleidoscópio", "Excentricidade", "Idiossincrasia", "Perspicácia", "Procrastinação", "Resiliência",
    "Serendipidade", "Efêmero", "Sempiterno", "Inexorável", "Voz", "Luz", "Paz", "Fé", "Sol", "Sal",
    "Umbigo", "Sovaco", "Canela", "Cotovelo", "Joelho", "Nuca", "Calcanhar", "Tornozelo", "Pulso", "Punho",
    // 63. Marcas de Carro e Luxo (Reforço)
    "Bugatti", "Maserati", "Alfa Romeo", "Land Rover", "Jaguar", "Volvo", "Scania", "Iveco", "Yamaha", "Suzuki",
    "Kawasaki", "Harley-Davidson", "Ducati", "Triumph", "Royal Enfield", "Bentley", "Rolls-Royce", "Aston Martin", "Lotus", "Mini Cooper",
    // 64. Capitais e Cidades que faltaram
    "Dacar", "Luanda", "Maputo", "Cabul", "Bagdá", "Damasco", "Beirute", "Amã", "Riad", "Ancara",
    "Teerã", "Islamabad", "Katmandu", "Daca", "Hanoi", "Manila", "Jacarta", "Camberra", "Wellington", "Suva",
    "Pretória", "Abuja", "Argel", "Trípoli", "Cartum", "Adis Abeba", "Mogadíscio", "Kinshasa", "Brazzaville", "Libreville",
    // 65. Eletrodomésticos e Tecnologia (Retro e Atual)
    "Videocassete", "DVD", "Blu-ray", "Walkman", "Discman", "MP3", "iPod", "Bipe", "Pager", "Fax",
    "Máquina de Datilografar", "Toca-discos", "Vinil", "Fita Cassete", "Disquete", "CD", "Pen Drive", "HD Externo", "Cartão de Memória", "Nuvem",
    "Smartwatch", "Drone", "VR", "Impressora 3D", "Robô", "Assistente Virtual", "Alexa", "Siri", "Google Home", "Chatbot",
    // 66. Circo e Espetáculo
    "Circo", "Lona", "Picadeiro", "Arquibancada", "Bilheteria", "Pipoca", "Algodão Doce", "Maçã do Amor", "Espetáculo", "Aplausos",
    "Palhaço", "Mágico", "Malabarista", "Trapezista", "Contorcionista", "Domador", "Equilibrista", "Atirador de Facas", "Engolidor de Espadas", "Mimico",
    "Monociclo", "Perna de Pau", "Globo da Morte", "Corda Bamba", "Trampolim", "Cama Elástica", "Canhão", "Rede", "Trapézio", "Bambolê",
    "Cartola", "Varinha", "Coelho", "Pombo", "Carta", "Lenço", "Truque", "Ilusão", "Fantasia", "Maquiagem",
    "Nariz Vermelho", "Sapatos Grandes", "Peruca", "Buzina", "Flor que espirra água", "Torta na cara", "Risada", "Sombra", "Marionete", "Fantoche",

    // 67. Culinária Japonesa e Asiática
    "Sushi", "Sashimi", "Temaki", "Niguiri", "Uramaki", "Hossomaki", "Hot Roll", "Joe", "Ceviche", "Carpaccio",
    "Yakisoba", "Lamen", "Udon", "Guioza", "Harumaki", "Rolinho Primavera", "Tempurá", "Teppan", "Robata", "Poke",
    "Shimeji", "Shitake", "Missoshiro", "Tofu", "Gohan", "Arroz Japonês", "Alga", "Nori", "Gergelim", "Cebolinha",
    "Salmão", "Peixe Branco", "Polvo", "Lula", "Camarão", "Kani", "Ova", "Cream Cheese", "Pepino",
    "Wasabi", "Gengibre", "Shoyu", "Agridoce", "Tarê", "Teriyaki", "Saquê", "Sorte","Trevo","Azar",
    "Hashi", "Pauzinhos", "Nozinhos", "Barca", "Rodízio", "Esteira", "Sudare", "Faca Japonesa", "Cerâmica", "Bambu",

    // 68. Frutos do Mar e Peixes (Específicos)
    "Camarão", "Lagostim", "Ostra", "Mexilhão", "Vieira", "Vôngole", "Marisco",
    "Polvo", "Lula", "Água-viva", "Caviar", "Ouriço", "Estrela-do-mar", "Coral", "Anêmona", "Marinha",
    "Bacalhau", "Tilápia", "Robalo", "Tainha", "Dourado", "Pintado", "Pacu",
    "Tambaqui", "Pirarucu", "Truta", "Linguado", "Namorado", "Badejo", "Pargo", "Garoupa", "Cavala", "Arenque",
    "Anchova", "Peixe-espada", "Peixe-palhaço", "Raia", "Moreia", "Baiacu", "Piranha", "Lambari",

    // 69. Higiene Pessoal e Banheiro (Identifiquei Escassez aqui)
    "Escova de Dentes", "Pasta de Dente", "Creme Dental", "Fio Dental", "Enxaguante", "Sabonete", "Shampoo", "Condicionador", "Creme de Pentear", "Gel",
    "Desodorante", "Perfume", "Colônia", "Hidratante", "Protetor Solar", "Repelente", "Talco", "Pomada", "Cotonete", "Algodão",
    "Papel Higiênico", "Lenço Umedecido", "Absorvente", "Coletor Menstrual", "Fralda", "Lâmina", "Barbeador", "Espuma de Barbear", "Pós-barba", "Pinça",
    "Cortador de Unha", "Lixa", "Esmalte", "Acetona", "Removedor", "Secador", "Chapinha", "Babyliss", "Pente", "Escova de Cabelo",
    "Toalha", "Roupão", "Touca", "Esponja", "Bucha", "Cesto", "Privada", "Vaso Sanitário", "Pia", "Chuveiro",
    "Banheira", "Torneira", "Ralo", "Espelho", "Box", "Cortina", "Tapete", "Lixeira", "Descarga", "Assento",

    // 70. Fazenda e Vida Rural (Identifiquei Escassez de estrutura)
    "Fazenda", "Sítio", "Chácara", "Rancho", "Horta", "Pomar", "Plantação", "Lavoura", "Pasto", "Curral",
    "Celeiro", "Silo", "Galinheiro", "Chiqueiro", "Cocheira", "Estábulo", "Aprisco", "Viveiro", "Tanque", "Açude",
    "Cerca", "Arame Farpado", "Porteira", "Mata-burro", "Estrada de Terra", "Trilha", "Ponte", "Moinho", "Catavento", "Poço",
    "Trator", "Arado", "Colheitadeira", "Carroça", "Charrete", "Carrinho de Mão", "Enxada", "Pá", "Foice", "Facão",
    "Espantalho", "Sela", "Ferradura", "Cabresto", "Rédea", "Chicote", "Berrante", "Viola", "Fogueira", "Rede",
    "Leite", "Queijo Fresco", "Coalhada", "Doce de Leite", "Ovo Caipira", "Galinha Caipira", "Torresmo", "Linguiça", "Feijão Tropeiro", "Café",

    // 71. Opostos e Contrastes (Conceitos que geram match rápido)
    "Dia", "Noite", "Claro", "Escuro", "Preto", "Branco", "Alto", "Baixo", "Gordo", "Magro",
    "Grande", "Pequeno", "Gigante", "Anão", "Quente", "Frio", "Céu", "Inferno", "Bem", "Mal",
    "Rico", "Pobre", "Jovem", "Velho", "Novo", "Usado", "Vida", "Morte", "Começo", "Fim",
    "Entrada", "Saída", "Aberto", "Fechado", "Cheio", "Vazio", "Tudo", "Nada", "Sempre", "Nunca",
    "Verdade", "Mentira", "Amor", "Ódio", "Guerra", "Paz", "Sol", "Lua", "Terra", "Mar",

    //Mix
    "Boneco de neve", "Mamona", "Zumbi","Esqueleto","Tumba",

    //Orka Vain
    "Orka Zoo","Orka Studio","Dethrone","Jinx","Diova"
];

export const palavrasEN = [
    //1. Objetos do cotidiano
    "Chair", "Table", "Sofa", "Bed", "Pillow", "Blanket", "Cushion", "Wardrobe", "Shelf", "Bookcase",
    "Door", "Window", "Curtain", "Rug", "Mirror", "Lamp", "Switch", "Outlet", "Fan", "Heater",
    "Refrigerator", "Freezer", "Stove", "Oven", "Microwave", "Pan", "Frying pan", "Plate", "Glass", "Cup",
    "Cutlery", "Knife", "Fork", "Spoon", "Board", "Blender", "Mixer", "Coffee maker", "Bottle", "Container",
    "Brush", "Comb", "Soap", "Shampoo", "Towel", "Paper", "Notebook", "Book", "Pen", "Pencil",
    "Eraser", "Sharpener", "Backpack", "Bag", "Wallet", "Key", "Lock", "Watch", "Cellphone", "Telephone",
    "Computer", "Keyboard", "Mouse", "Monitor", "Printer", "Charger", "Headphones", "Box", "Remote", "Television",
    "Radio", "Camera", "Glasses", "Umbrella", "Cap", "Hat", "Shirt", "Pants", "Shoes", "Socks",
    "Belt", "Coat", "Jacket", "Ladder", "Hammer", "Screwdriver", "Pliers", "Broom", "Mop", "Bucket",
    "Shovel", "Trash can", "Bag", "Cardboard box", "Tape", "Scissors", "Glue", "Envelope", "Calendar", "Planner",
    //2. Comida
    "Rice", "Beans", "Meat", "Chicken", "Fish", "Egg", "Bread", "Milk", "Cheese", "Butter",
    "Sugar", "Salt", "Oil", "Olive Oil", "Pasta", "Pizza", "Hamburger", "Sausage", "Ham", "Bacon",
    "Lettuce", "Tomato", "Carrot", "Potato", "Onion", "Garlic", "Broccoli", "Cabbage", "Spinach", "Corn",
    "Peas", "Brown Rice", "Black Beans", "Lentils", "Chickpeas", "Soy", "Mushroom", "Pumpkin", "Zucchini", "Eggplant",
    "Cucumber", "Bell Pepper", "Apple", "Banana", "Orange", "Grape", "Mango", "Strawberry", "Pineapple", "Lemon",
    "Watermelon", "Melon", "Pear", "Papaya", "Kiwi", "Nuts", "Peanuts", "Walnuts", "Almonds", "Yogurt",
    "Cream Cheese", "Cream", "Ice Cream", "Cake", "Pie", "Cookie", "Biscuit", "Chocolate", "Candy", "Honey",
    "Jam", "Pudding", "Mousse", "Cereal", "Oats", "Flour", "Wheat", "Green Corn", "Coffee", "Tea",
    "Juice", "Soda", "Water", "Wine", "Beer", "Sauce", "Ketchup", "Mustard", "Mayonnaise", "Vinegar",
    "Pepper", "Oregano", "Basil", "Cinnamon", "Dark Chocolate", "Condensed Milk", "Heavy Cream", "Rice Pudding", "Cheese Bread", "Chocolate Cake",
    //3. Profissões
    "Doctor", "Nurse", "Dentist", "Veterinarian", "Pharmacist", "Psychologist", "Physiotherapist", "Nutritionist", "Therapist", "Paramedic",
    "Teacher", "Educator", "Pedagogue", "Tutor", "Instructor", "Researcher", "Scientist", "Historian", "Geographer", "Philosopher",
    "Engineer", "Architect", "Urban Planner", "Designer", "Illustrator", "Animator", "Programmer", "Developer", "Analyst", "Technician",
    "Electrician", "Plumber", "Bricklayer", "Carpenter", "Woodworker", "Painter", "Welder", "Mechanic", "Machinist", "Operator",
    "Driver", "Pilot", "Conductor", "Delivery Worker", "Mail Carrier", "Truck Driver", "Taxi Driver", "Navigator", "Commander", "Captain",
    "Lawyer", "Judge", "Prosecutor", "Detective", "Forensic Expert", "Clerk", "Defender", "Attorney", "Notary", "Auditor",
    "Accountant", "Economist", "Administrator", "Manager", "Consultant", "Broker", "Appraiser", "Banker", "Treasurer", "Financial Analyst",
    "Salesperson", "Attendant", "Cashier", "Shop Assistant", "Receptionist", "Merchant", "Representative", "Negotiator", "Distributor", "Buyer",
    "Cook", "Chef", "Baker", "Pastry Chef", "Butcher", "Fishmonger", "Caterer", "Waiter", "Bartender", "Sommelier",
    //4. Natureza
    "Tree", "Forest", "Jungle", "Woods", "Grove", "Field", "Plain", "Mountain", "Range", "Hill",
    "Valley", "Desert", "Oasis", "Beach", "Coast", "Island", "Archipelago", "Ocean", "Sea", "Lake",
    "Lagoon", "River", "Stream", "Waterfall", "Spring", "Delta", "Estuary", "Swamp", "Marsh", "Mangrove",
    "Snow", "Ice", "Hail", "Rain", "Storm", "Wind", "Breeze", "Hurricane", "Tornado", "Cyclone",
    "Cloud", "Mist", "Fog", "Dew", "Frost", "Sun", "Moon", "Star", "Planet", "Comet",
    "Asteroid", "Sky", "Horizon", "Aurora", "Eclipse", "Volcano", "Crater", "Lava", "Rock", "Stone",
    "Sand", "Earth", "Soil", "Clay", "Mineral", "Crystal", "Quartz", "Coal", "Iron", "Gold",
    "Silver", "Copper", "Plant", "Flower", "Leaf", "Root", "Seed", "Trunk", "Branch", "Bark",
    "Moss", "Algae", "Fungus", "Coral", "Reef", "Savanna", "Tundra", "Taiga", "Biome", "Ecosystem",
    //5. Lugares
    "City", "Town", "Village", "Neighborhood", "Street", "Avenue", "Square", "Park", "Garden", "Bridge",
    "Tunnel", "Highway", "Road", "Crossroad", "Roundabout", "Downtown", "Suburb", "District", "Capital", "Region",
    "Country", "State", "Province", "Continent", "Map", "Border", "Port", "Airport", "Station", "Terminal",
    "Hospital", "Clinic", "Pharmacy", "School", "College", "University", "Library", "Museum", "Theater", "Cinema",
    "Church", "Temple", "Sanctuary", "Monastery", "Cathedral", "Palace", "Castle", "Fortress", "Tower", "Monument",
    "Hotel", "Inn", "Hostel", "Restaurant", "Cafe", "Bar", "Market", "Fair", "Store", "Mall",
    "Factory", "Warehouse", "Depot", "Workshop", "Office", "Company", "Industry", "Bank", "Post Office", "Registry",
    "Police Station", "Barracks", "Court", "City Hall", "Council", "Stadium", "Gymnasium", "Arena", "Pool", "Gym",
    "Zoo", "Aquarium", "Observatory", "Planetarium", "Laboratory", "Cemetery", "Garage", "Parking Lot", "Bus Terminal", "Gas Station",
    //6. Animals
    "Bee", "Eagle", "Moose", "Spider", "Whale", "Butterfly", "Dog", "Camel", "Kangaroo", "Horse",
    "Snake", "Rabbit", "Owl", "Crocodile", "Elephant", "Squirrel", "Falcon", "Rooster", "Cat", "Giraffe",
    "Dolphin", "Hamster", "Hippopotamus", "Alligator", "Lion", "Leopard", "Wolf", "Otter", "Monkey", "Bat",
    "Jaguar", "Sheep", "Panda", "Parrot", "Duck", "Peacock", "Fish", "Penguin", "Pig", "Frog",
    "Fox", "Rat", "Rhinoceros", "Toad", "Serpent", "Turtle", "Tiger", "Shark", "Bear", "Cow",
    "Deer", "Zebra", "Crab", "Starfish", "Lobster", "Octopus", "Jellyfish", "Snail", "Lizard", "Iguana",
    "Ant", "Beetle", "Ladybug", "Scorpion", "Ray", "Eel", "Tuna", "Sardine", "Seagull", "Swallow",
    "Raven", "Dove", "Swan", "Goose", "Chicken", "Turkey", "Quail", "Boar", "Badger", "Weasel",
    "Seal", "Sea Lion", "Walrus", "Antelope", "Buffalo", "Bison", "Meerkat", "Lemur", "Orangutan", "Chimpanzee",
    //7. Fantasy Elements
    "Dragon", "Phoenix", "Unicorn", "Griffin", "Chimera", "Hydra", "Kraken", "Giant", "Dwarf", "Elf",
    "Orc", "Goblin", "Troll", "Demon", "Angel", "Seraph", "Titan", "Spirit", "Ghost", "Specter",
    "Shadows", "Light", "Darkness", "Magic", "Spell", "Enchantment", "Curse", "Runes", "Relic", "Artifact",
    "Amulet", "Talisman", "Staff", "Wand", "Grimoire", "Scroll", "Potion", "Elixir", "Crystal", "Obsidian",
    "Mithril", "Adamantium", "Aether", "Mana", "Essence", "Energy", "Portal", "Dimension", "Realm", "Empire",
    "Throne", "Crown", "Prophecy", "Destiny", "Chaos", "Order", "Balance", "Abyss", "Vortex", "Labyrinth",
    "Tower", "Fortress", "Citadel", "Temple", "Sanctuary", "Altar", "Lightning", "Flame", "Ice", "Ogre",
    "Wand", "Fairy", "Ancient", "Blood", "Bone", "Scale", "Wing", "Claw", "Eye", "Mask",
    "Sword", "Axe", "Bow", "Arrow", "Shield", "Armor", "Blade", "Hammer", "Orb", "Sigil",
    //8. Emotions
    "Joy", "Sadness", "Anger", "Fear", "Disgust", "Surprise", "Love", "Hate", "Hope", "Despair",
    "Anxiety", "Calm", "Peace", "Tension", "Pride", "Shame", "Guilt", "Relief", "Euphoria", "Melancholy",
    "Loneliness", "Longing", "Empathy", "Compassion", "Envy", "Jealousy", "Admiration", "Respect", "Trust", "Distrust",
    "Courage", "Cowardice", "Determination", "Doubt", "Faith", "Skepticism", "Gratitude", "Frustration", "Satisfaction", "Disappointment",
    "Enthusiasm", "Apathy", "Curiosity", "Boredom", "Interest", "Fascination", "Nostalgia", "Acceptance", "Rejection", "Humiliation",
    "Regret", "Remorse", "Pleasure", "Pain", "Comfort", "Discomfort", "Awe", "Dread", "Panic", "Serenity",
    "Shyness", "Optimism", "Pessimism", "Motivation", "Discouragement", "Affection", "Fondness", "Rage", "Resentment", "Bitterness",
    "Confusion", "Clarity", "Vanity", "Understanding", "Tolerance", "Irritation", "Exhaustion", "Relief", "Delight", "Wonder",
    //9. Body Parts
    "Head", "Face", "Forehead", "Eyebrow", "Eyelid", "Nose", "Mouth", "Lip", "Tooth", "Tongue",
    "Jaw", "Chin", "Cheek", "Ear", "Neck", "Nape", "Throat", "Clavicle", "Shoulder", "Armpit",
    "Arm", "Forearm", "Elbow", "Wrist", "Hand", "Palm", "Finger", "Nail", "Thumb", "Index",
    "Middle", "Ring", "Pinky", "Thorax", "Chest", "Rib", "Abdomen", "Belly", "Navel", "Hip",
    "Waist", "Groin", "Back", "Lower Back", "Spine", "Scapula", "Pelvis", "Buttock", "Thigh", "Knee",
    "Calf", "Shin", "Ankle", "Heel", "Foot", "Sole", "Instep", "Big Toe", "Joint", "Cartilage",
    "Muscle", "Tendon", "Ligament", "Skin", "Pores", "Vein", "Artery", "Lung", "Heart", "Stomach",
    "Liver", "Kidney", "Intestine", "Esophagus", "Trachea", "Larynx", "Diaphragm", "Pancreas", "Spleen", "Bladder",
    "Brain", "Spinal Cord", "Nerve", "Gland", "Hormone", "Retina", "Iris", "Cornea", "Pupil", "Meninges",
    //10. Music and musical instruments
    "Music", "Melody", "Harmony", "Rhythm", "Beat", "Tone", "Note", "Chord", "Scale", "Silence",
    "Sound", "Echo", "Volume", "Vibration", "Lyrics", "Chorus", "Verse", "Song", "Album", "Concert",
    "Orchestra", "Band", "Choir", "Conductor", "Singer", "Composer", "Performer", "Musician", "Producer", "Artist",
    "Piano", "Keyboard", "Organ", "Violin", "Viola", "Cello", "Double Bass", "Guitar", "Acoustic Guitar", "Bass",
    "Drums", "Drum", "Snare", "Cymbal", "Xylophone", "Marimba", "Flute", "Piccolo", "Clarinet", "Oboe",
    "Saxophone", "Trumpet", "Trombone", "Tuba", "Cornet", "Harmonica", "Accordion", "Mandolin", "Ukulele", "Harp",
    "Lyre", "Sitar", "Banjo", "Tambourine", "Berimbau", "Percussion", "Orchestration", "Improvisation", "Composition", "Arrangement",
    //11. Human relationships
    "Friendship", "Enmity", "Partnership", "Alliance", "Rivalry", "Competition", "Cooperation", "Conflict", "Bond", "Solidarity",
    "Love", "Passion", "Affection", "Attachment", "Distance", "Separation", "Union", "Marriage", "Divorce", "Family",
    "Relative", "Sibling", "Parenthood", "Motherhood", "Fatherhood", "Kinship", "Care", "Protection", "Support", "Trust",
    "Lover", "Couple", "Companion", "Partner", "Ex", "Crush", "Suitor", "Boss", "Employee", "Colleague",
    "Associate", "Client", "Supplier", "Leader", "Follower", "Mentor", "Apprentice", "Ally", "Enemy", "Traitor",
    "Accomplice", "Witness", "Stranger", "Acquaintance", "Neighbor", "Guest", "Host", "Rival", "Mediator", "Opponent",
    //12. Technology
    "Technology", "Machine", "System", "Device", "Appliance", "Equipment", "Tool", "Mechanism", "Circuit", "Processor",
    "Computer", "Server", "Terminal", "Console", "Laptop", "Tablet", "Phone", "Smartphone", "Screen", "Monitor",
    "Keyboard", "Mouse", "Sensor", "Camera", "Microphone", "Speaker", "Headphones", "Battery", "Charger", "Cable",
    "Network", "Internet", "Connection", "Signal", "Satellite", "Antenna", "Cloud", "Database", "File", "Storage",
    "Software", "Application", "Program", "Algorithm", "Code", "Script", "Interface", "Platform", "Operating System", "Update",
    "Firewall", "Encryption", "Security", "Privacy", "Leak", "Backup", "Automation", "Robot", "Artificial Intelligence", "Simulation",
    //13. Abstract, moral and philosophical concepts
    "Justice", "Injustice", "Truth", "Lie", "Good", "Evil", "Ethics", "Morality", "Virtue", "Sin",
    "Freedom", "Oppression", "Right", "Duty", "Responsibility", "Guilt", "Innocence", "Judgment", "Forgiveness", "Redemption",
    "Life", "Death", "Birth", "End", "Beginning", "Fate", "Chance", "Choice", "Consequence", "Meaning",
    "Existence", "Consciousness", "Identity", "Ego", "Soul", "Spirit", "Will", "Desire", "Intention", "Purpose",
    "Time", "Eternity", "Infinity", "Void", "Nothingness", "Totality", "Chaos", "Order", "Balance", "Rupture",
    "Apocalypse", "Collapse", "Creation", "Destruction", "Renewal", "Hope", "Despair", "Fear", "Courage", "Faith",
    //14. Hand tools
    "Hammer", "Sledgehammer", "Mallet", "Wrench", "Adjustable Wrench", "Screwdriver", "Phillips Screwdriver", "Pliers", "Cutting Pliers", "Locking Pliers",
    "Handsaw", "Hacksaw", "File", "Chisel", "Plane", "Tape Measure", "Level", "Square", "Compass", "Ruler",
    "Utility Knife", "Pocket Knife", "Scissors", "Clamp", "C Clamp", "Vise", "Punch", "Cold Chisel", "Spatula", "Trowel",
    "Shovel", "Hoe", "Pickaxe", "Rake", "Sickle", "Axe", "Rubber Mallet", "Wire Brush", "Sandpaper", "Scraper",
    //15. Machines
    "Machine", "Motor", "Engine", "Generator", "Compressor", "Lathe", "Milling Machine", "Press", "Conveyor", "Elevator",
    "Crane", "Excavator", "Backhoe", "Tractor", "Harvester", "Concrete Mixer", "Crusher", "Drilling Machine", "Drill", "Screwdriver Machine",
    "Electric Saw", "Circular Saw", "Band Saw", "Polisher", "Sander", "Planer", "Welding Machine", "Inverter", "Transformer", "Control Panel",
    "Pump", "Valve", "Fan", "Turbine", "Boiler", "Reactor", "3D Printer", "Industrial Robot", "CNC Machine", "Controller",
    //16. Buildings
    "House", "Building", "Apartment", "Duplex", "Warehouse", "Factory", "Workshop", "Store", "School", "Hospital",
    "Clinic", "Church", "Temple", "Cathedral", "Chapel", "Castle", "Fortress", "Palace", "Tower", "Bridge",
    "Viaduct", "Tunnel", "Road", "Highway", "Dam", "Dike", "Port", "Airport", "Station", "Terminal",
    "Stadium", "Gymnasium", "Arena", "Theater", "Cinema", "Museum", "Library", "Mall", "Market", "Fair",
    "Hotel", "Inn", "Hostel", "Restaurant", "Bar", "Cafe", "Gas Station", "Garage", "Parking Structure", "Depot",
    //17. Rooms
    "Room", "Living Room", "Dining Room", "Bedroom", "Suite", "Kitchen", "Pantry", "Bathroom", "Restroom", "Laundry Room",
    "Service Area", "Office", "Library", "Studio", "Workshop Room", "Closet", "Hallway", "Hall", "Entrance", "Balcony",
    "Terrace", "Attic", "Basement", "Cellar", "Garage", "Storage Room", "Utility Room", "File Room", "Anteroom", "Dressing Room",
    "Children Room", "Guest Room", "Game Room", "Meeting Room", "Control Room", "Technical Room", "Warehouse Room", "Archive", "Lobby", "Back Room",
    //18. Construction materials
    "Concrete", "Cement", "Sand", "Gravel", "Mortar", "Lime", "Plaster", "Stucco", "Putty", "Asphalt",
    "Brick", "Block", "Slab", "Beam", "Column", "Rebar", "Steel", "Iron", "Aluminum", "Copper",
    "Wood", "Plywood", "MDF", "OSB", "Plastic", "PVC", "Glass", "Fiber", "Rubber", "Insulation",
    "Roof Tile", "Ceramic", "Porcelain Tile", "Tile", "Granite", "Marble", "Stone", "Slate", "Quartz", "Coating",
    "Paint", "Varnish", "Sealer", "Waterproofing", "Glue", "Adhesive", "Screw", "Nail", "Wall Plug", "Ring",
    //19. Colors
    "White", "Black", "Gray", "Silver", "Gold",
    "Red", "Blue", "Green", "Yellow", "Orange", "Purple", "Pink", "Brown",
    "Beige", "Cream", "Wine", "Burgundy", "Turquoise", "Cyan", "Magenta",
    "Indigo", "Violet", "Lilac", "Lavender", "Olive", "Moss", "Emerald",
    "Sapphire", "Amber", "Caramel", "Chocolate", "Sand", "Graphite",
    "Coral", "Peach", "Salmon", "Mustard", "Rust",
    "Light blue", "Dark blue", "Light green", "Dark green", "Light gray", "Dark gray",
    //20. Physical states
    "Solid", "Liquid", "Gas", "Plasma",
    "Hard", "Soft", "Rigid", "Flexible", "Elastic",
    "Fragile", "Resistant", "Broken", "Intact", "Damaged",
    "Smooth", "Rough", "Porous", "Polished",
    "Dry", "Wet", "Damp", "Soaked",
    "Hot", "Cold", "Frozen", "Warm",
    "Heavy", "Light", "Dense", "Hollow", "Solid mass",
    "Transparent", "Opaque", "Translucent",
    "Open", "Closed", "Locked", "Unlocked",
    "Full", "Empty", "Cracked", "Bent", "Folded",
    "Stable", "Unstable", "Fixed", "Movable",
    "New", "Used", "Old", "Ancient", "Rusty",
    //21. Sports and sporting goods
    "Soccer", "Basketball", "Volleyball", "Handball", "Futsal", "Tennis", "Table tennis", "Badminton", "Baseball", "Softball",
    "Rugby", "Cricket", "Hockey", "Ice hockey", "Field hockey", "Golf", "Polo", "Bowling", "Bocce", "Peteca",
    "Swimming", "Diving", "Water polo", "Surfing", "Windsurfing", "Kitesurfing", "Skateboarding", "Roller skating", "Cycling", "Mountain biking",
    "Athletics", "Running", "Marathon", "Jumping", "Throwing",
    "Boxing", "Judo", "Karate", "Taekwondo", "Jiu-jitsu", "Fencing", "Wrestling", "Muay thai",
    "Climbing", "Mountaineering", "Skiing", "Snowboarding",
    "Ball", "Soccer ball", "Basketball ball", "Racket", "Tennis racket", "Ping pong paddle",
    "Bat", "Stick", "Glove", "Helmet", "Shin guard", "Knee pad", "Elbow pad",
    "Net", "Goal", "Hoop", "Target", "Track", "Court", "Field",
    //22. Hobbies
    "Reading", "Writing", "Drawing", "Painting", "Illustration", "Sculpture", "Graffiti",
    "Photography", "Filming", "Editing", "Animation",
    "Music", "Singing", "Composition", "Instrument", "Acoustic guitar", "Electric guitar", "Piano", "Keyboard", "Drums",
    "Games", "Video game", "Board game", "Card game", "RPG", "Puzzle",
    "Programming", "Coding", "Modeling", "3D printing",
    "Crafting", "Crochet", "Knitting", "Sewing", "Embroidery", "Woodworking", "Ceramics",
    "Cooking", "Baking", "Confectionery",
    "Gardening", "Horticulture", "Cultivation",
    "Observation", "Astronomy", "Telescope",
    "Collecting", "Miniatures", "Stamps", "Coins", "Cards",
    "Origami", "Calligraphy", "Chess", "Checkers", "Sudoku",
    "Meditation", "Yoga", "Walking", "Hiking", "Camping",
    //23. Means of transportation
    "Car", "Automobile", "Truck", "Pickup", "Bus", "Minibus", "Van",
    "Motorcycle", "Scooter", "Bicycle", "Tricycle", "Quadricycle",
    "Train", "Subway", "Railcar", "Locomotive", "Tram", "Monorail",
    "Airplane", "Jet", "Seaplane", "Glider", "Helicopter", "Airship",
    "Ship", "Boat", "Speedboat", "Yacht", "Ferry", "Canoe", "Kayak", "Submarine",
    "Cargo ship", "Oil tanker", "Aircraft carrier",
    "Kick scooter", "Hoverboard",
    "Electric car", "Hybrid car",
    "Sled", "Cable car", "Funicular",
    "Cart", "Carriage",
    "Spaceship", "Rocket", "Space shuttle",
    "Balloon",
    //24. Clothing
    "T-shirt", "Blouse", "Tank top", "Sweater", "Pullover",
    "Dress", "Skirt", "Shorts", "Bermuda shorts", "Jumpsuit",
    "Suit", "Blazer", "Vest", "Overcoat", "Poncho",
    "Pajamas", "Bathrobe", "Uniform",
    "Underwear", "Briefs", "Panties", "Bra",
    "Tights", "Leggings",
    "Bikini", "Swimsuit", "Swim briefs",
    "Sneakers", "Boots", "Flip flops", "Sandals", "Flats", "Combat boots",
    "Gloves", "Scarf", "Necktie", "Bow tie",
    "Bracelet", "Necklace", "Ring", "Earring",
    "Hood", "Beanie",
    "Apron", "Military uniform", "Costume"
];