export const palavrasPT = [
  "3D", "Abacaxi", "Abdômen", "Abelha", "Aberto", "Abismo", "Abóbora", "Abobrinha", "Absinto", "Absorvente",
  "Abuja", "Academia", "Açaí", "Ação", "Acaso", "Ace", "Aceitação", "Acer", "Acetona", "aço",
  "Aço", "Acorde", "Acordeão", "Açougueiro", "Acrílica", "Acrofobia", "Açúcar", "Açude", "Adaga", "Adamantium",
  "Adega", "Ades", "Adesivo", "Adidas", "Adis Abeba", "Administrador", "Admiração", "Adoção", "Advogado", "Aeroporto",
  "Afeganistão", "Afeto", "Afilhada", "Afilhado", "África do Sul", "Afrodite", "Ágata", "Agenda", "Agogô", "Agorafobia",
  "Agridoce", "água", "Água", "Águia", "Airfryer", "Ajax", "Akita", "Albânia", "Albergue", "Albert Einstein",
  "Álbum", "Alce", "Alcorão", "Aldeia", "Alecrim", "Alegria", "Alemanha", "Alemão", "Alergia", "Alexa",
  "Alexandre o Grande", "Alfa Romeo", "Alface", "Alga", "Álgebra", "Algodão", "Algoritmo", "Alho", "Ali", "Aliado",
  "Aliança", "Alicate", "Alívio", "Alma", "Almofada", "Almoxarifado", "Alpinismo", "Alquimia", "Altar", "Alto",
  "Altruísta", "Altura", "Alumínio", "Alvo", "Amã", "Amaciante", "Amante", "Amarelinha", "Amarelo", "Amargo",
  "Amassado", "Amazon", "Âmbar", "Ambulância", "AMD", "Amêndoa", "Amendoim", "Ametista", "Amígdala", "Amizade",
  "Amor", "Amsterdã", "Amuleto", "Analista", "Anão", "Ancara", "Anchova", "Ancinho", "Andorinha", "Andorra",
  "Anel", "Anelar", "Anêmona", "Anfitrião", "Angola", "Angorá", "Anil", "Animação", "Animador", "Anitta",
  "Aniversário", "Anjo", "Ano Novo", "Ansiedade", "Ansioso", "Antebraço", "Antena", "Antessala", "Antigo", "Antílope",
  "Aorta", "Apagador", "Aparelho", "Apartamento", "Apatia", "Apego", "Apêndice", "Aplausos", "Aplicativo", "Apocalipse",
  "Apolo", "Apontador", "Aposentadoria", "Apple", "Aprendiz", "Aprisco", "Aquaman", "Aquarela", "Aquário", "aquático",
  "Aquecedor", "Aquiles", "Arábia Saudita", "Aracaju", "Aracnofobia", "Arado", "Aragorn", "Arame", "Aranha", "Arcanjo",
  "Arco", "Ardósia", "Área", "Areia", "Arena", "Arenque", "Ares", "Argamassa", "Argel", "Argélia",
  "Argentina", "Argila", "Argola", "Argônio", "Áries", "Armadura", "Armani", "Armário", "Armazém", "Armênia",
  "Aromatizador", "Arquibancada", "Arquipélago", "Arquiteto", "Arquivo", "Arraia", "Arremesso", "Arrependimento", "Arroz", "Arruda",
  "Arsenal", "Artefato", "Ártemis", "Artéria", "Artesanato", "Articulação", "artificial", "Árvore", "Ás", "Asa",
  "Ascendente", "Asfalto", "Ash", "Asma", "Áspero", "Aspirador", "Assento", "Assistente", "Assombração", "Assunção",
  "Asteroide", "Aston Martin", "Astral", "Astronomia", "Asus", "Atabaque", "Ateliê", "Atena", "Atenas", "Atendente",
  "Athletico Paranaense", "Atirador", "Atlético de Madrid", "Atlético Mineiro", "Atletismo", "Átomo", "Ator", "Atriz", "Atualização", "Atum",
  "Auckland", "Audi", "Auditor", "Audrey Hepburn", "Aura", "Aurora", "Austrália", "Áustria", "Automação", "Automóvel",
  "Autorama", "Avaí", "Avalanche", "Avaliador", "Avarento", "Aveia", "Avenida", "Avental", "Aventura", "Avião",
  "aviões", "Avó", "Avô", "Avon", "Axé", "Axila", "Azaleia", "Azar", "Azedo", "Azeite",
  "Azerbaijão", "Azul", "Azulejo", "Babosa", "Babyliss", "Bacalhau", "Bach", "Bacia", "Backup", "Baço",
  "Bacon", "Bactéria", "Badejo", "Badminton", "Bagdá", "Bagunçado", "Bahamas", "Bahia", "Bahrein", "Baiacu",
  "Bairro", "Baixo", "Balada", "Balão", "Balconista", "Balde", "Baleia", "Ballet", "Balsa", "Bamba",
  "Bambolê", "Bambu", "Banana", "Bancário", "Banco", "Banco do Brasil", "Banda", "Bandolim", "Bangkok", "Bangladesh",
  "Banheira", "Banheiro", "Banjo", "Bar", "barba", "Barbados", "Bárbaro", "Barbeador", "Barbear", "Barbie",
  "Barca", "Barcelona", "Barco", "Bardo", "Barney", "Barra", "Barragem", "Barriga", "Bart", "Bartender",
  "basquete", "Basquete", "Basset", "Bastão", "Batata", "Batedeira", "Bateria", "Batida", "Batizado", "Batman",
  "Bayern de Munique", "Beagle", "Bebê", "Beethoven", "Bege", "Begônia", "Beijinho", "Beirute", "Beisebol", "Belém",
  "Bélgica", "Belize", "Belo Horizonte", "Belzebu", "Bem", "Benfica", "Bengal", "Benin", "Bentley", "Berílio",
  "Berimbau", "Berinjela", "Berlim", "Bermuda", "Berna", "Bernardo", "Berrante", "Besouro", "Betoneira", "Bexiga",
  "Beyoncé", "Bíblia", "Biblioteca", "Bicho", "Bicicleta", "bico", "Biden", "Bielorrússia", "Big Bang", "bike",
  "Bila", "Bilheteria", "Bílis", "Bill Gates", "Bimotor", "Biologia", "Bioma", "Bipe", "Biplano", "Biquíni",
  "Bisão", "Bisavó", "Bisavô", "Biscoito", "Bisneta", "Bisneto", "Bitcoin", "Blazer", "Bloco", "Blog",
  "Blu-ray", "Blues", "Bluetooth", "Blusa", "BMW", "Boa Vista", "Bob Esponja", "Boca", "Boca Juniors", "Bocha",
  "Bochecha", "Bogotá", "Bola", "Bolero", "Boleto", "Boliche", "Bolívia", "Bolo", "Bolsa", "Bolso",
  "Bolsonaro", "Bomba", "Bombaim", "Bombeiro", "Bombom", "Bombril", "Bonde", "Bondoso", "Boné", "Boneca",
  "Boneco", "Bonito", "Bonsai", "Borboleta", "Bordado", "Border", "Bordô", "Boreal", "Boro", "borracha",
  "Borracha", "Borussia Dortmund", "Bósnia", "Bosque", "Bossa Nova", "Bota", "Botafogo", "Botão", "Boticário", "Botsuana",
  "Bowser", "Box", "Boxe", "Boxer", "Braço", "Bradesco", "Branca", "Branco", "Brasil", "Brasileirão",
  "Brasília", "Brazzaville", "break", "Brejo", "Brigadeiro", "Brinco", "Brisa", "Brita", "Britadeira", "Brócolis",
  "Bromélia", "Bronquite", "Bronze", "Brunei", "Bruxelas", "Bucha", "Buda", "Budapeste", "Buenos Aires", "Búfalo",
  "Bugatti", "Bulgária", "Bulldog", "Bulls", "Buraco", "Burger King", "Burkina Faso", "burro", "Burro", "Burundi",
  "Butão", "Buzina", "C&A", "cabeça", "Cabeça", "Cabelo", "Cabo", "Cabo Verde", "Cabresto", "Cabul",
  "Caçarola", "Cachaça", "Cachecol", "Cacheta", "Cachoeira", "Cachorro", "Cacto", "Cadarço", "Cadeira", "Cadente",
  "Caderno", "Café", "Cafeteira", "Caiaque", "Caipira", "Caipirinha", "Cairo", "Caixa", "Cajado", "Cajuzinho",
  "Cal", "calça", "Calça", "Calcanhar", "Calcinha", "Cálcio", "Calculadora", "Cálculo", "Caldeira", "Caldo",
  "Caleidoscópio", "Calendário", "Caligrafia", "Calma", "Calmo", "Calvin Klein", "Cama", "Câmara", "Camarão", "Camarim",
  "Camarões", "Camberra", "Camboja", "Camelo", "Câmera", "Caminhada", "Caminhão", "Caminhoneiro", "Caminhonete", "Camisa",
  "Camiseta", "Camomila", "Campinas", "Camping", "campo", "Campo", "Campo Grande", "Camurça", "cana", "Canadá",
  "Canção", "Câncer", "Canela", "Caneleira", "Caneta", "Canetão", "Canetinha", "Canguru", "Canhão", "Canino",
  "Canivete", "Canjica", "Canoa", "Canon", "Canson", "Canto", "Cantor", "Cantora", "Caos", "Capacete",
  "Capela", "Capital", "Capitão", "Capitão América", "Cappuccino", "Capricórnio", "Capuz", "Cáqui", "cara", "Cara",
  "Caracas", "Caracol", "Caramelo", "Caranguejo", "Caratê", "Carbono", "cargueiro", "Cárie", "Carimbo", "Carinho",
  "Carlos Drummond", "Carmesim", "Carnaval", "Carne", "Carolina", "Carpaccio", "Carpinteiro", "Carregador", "Carrinho", "Carro",
  "Carroça", "Carta", "Cartão", "Cartas", "Carteira", "Carteiro", "Cartilagem", "Cartola", "Cartolina", "Cartório",
  "Cartum", "Carvão", "Casa", "Casablanca", "Casaco", "Casal", "Casamento", "Casca", "Cassete", "Castanha",
  "Castelo", "Catar", "Catavento", "Catedral", "Cavala", "Cavalete", "Cavalo", "Cavaquinho", "Caviar", "Cazaquistão",
  "CD", "Ceará", "Cebola", "Cebolinha", "Celeiro", "Celtics", "Célula", "Celular", "Cemitério", "Cena",
  "Cenoura", "Centauro", "Central", "Centro", "Cera", "Cerâmica", "Cerca", "Cereal", "Cérebro", "Cerveja",
  "Cesta", "Cesto", "Ceticismo", "Cetim", "Céu", "Ceviche", "Chá", "Chácara", "Chade", "Chakra",
  "Chaleira", "Chama", "Champanhe", "Champions League", "Chanel", "Chapecoense", "Chapéu", "Chapinha", "Charlie Chaplin", "Charrete",
  "Chatbot", "Chave", "Che Guevara", "Cheese", "Chef", "Chefe", "Cheio", "Chelsea", "Cheque", "Chevrolet",
  "Chicago", "Chicote", "Chihuahua", "Chile", "Chimarrão", "Chimpanzé", "China", "Chinelo", "Chipre", "Chiqueiro",
  "Chocolate", "Chocotone", "Chopp", "Choque", "Chow", "Chumbo", "Chun-Li", "Churchill", "Churrasco", "Churros",
  "chuva", "Chuva", "Chuveiro", "Ciano", "Cicatriz", "Ciclismo", "Ciclone", "Ciclope", "Cidade", "Cidadela",
  "Cidra", "Científica", "Cientista", "Cílios", "Cimento", "Cinema", "Cingapura", "Cinto", "Cintura", "Cinturão",
  "Cinza", "Circo", "Circuito", "circular", "Cisne", "Citrino", "Ciúme", "Clareza", "Clarice Lispector", "Clarinete",
  "claro", "Claro", "Clássica", "Claustrofobia", "Clavícula", "Cleópatra", "Clérigo", "Cliente", "Clínica", "Clips",
  "Cloro", "Closet", "CNC", "Coalhada", "Cobertor", "Cobra", "Cobre", "Coca-Cola", "Cocada", "Cóccix",
  "Cocheira", "Cocker", "coco", "Codificação", "Código", "Codorna", "Coelhinho da Páscoa", "Coelho", "Coentro", "Cofre",
  "Cogumelo", "Cola", "Colada", "Colagem", "Colapso", "Colar", "Colecionismo", "Colega", "Colégio", "Colesterol",
  "Colete", "Coletor", "Colgate", "Colheitadeira", "Colher", "Colina", "Collie", "Colômbia", "Colônia", "Coluna",
  "com", "Comadre", "Comandante", "Começo", "Comédia", "Comentário", "Comerciante", "Cometa", "Comores", "Compadre",
  "Compaixão", "Companheira", "Companheiro", "Compartilhamento", "Compasso", "Compensado", "Competição", "Composição", "Compositor", "Comprador",
  "Compreensão", "Compressor", "Comprimido", "Computador", "Concerto", "Concreto", "Condenação", "Condensado", "Condicionador", "Condutor",
  "Conexão", "Confeitaria", "Confeiteiro", "Confiança", "Conflito", "Conforto", "Confusão", "Congo", "Conhaque", "Conhecido",
  "Consciência", "Consequência", "Console", "Consultor", "Contador", "Continente", "Contorcionista", "Contrabaixo", "Contrato", "Controlador",
  "Controle", "Conversível", "Convidado", "Convívio", "Coon", "Cooperação", "Copa", "Copa do Mundo", "Copas", "Copenhague",
  "Copo", "Coquetel", "Cor", "Coração", "Coragem", "Corajoso", "Coral", "Corda", "Cordão", "Coreia do Norte",
  "Coreia do Sul", "Coringa", "Corinthians", "Coritiba", "Córnea", "Corneta", "Coroa", "Corredor", "Córrego", "Correio",
  "Corretivo", "Corretor", "corrida", "Corrida", "Cortador", "corte", "Corte", "Cortina", "Coruja", "Corvo",
  "Cosmopolitan", "Costa", "Costa do Marfim", "Costa Rica", "Costas", "Costela", "Costura", "Cotonete", "Cotoveleira", "Cotovelo",
  "Coturno", "Country", "Couro", "Couve", "Covardia", "Cowboys", "Coxa", "Cozinha", "Cozinheiro", "Crachá",
  "Cratera", "Cravo", "Cream", "Crédito", "Creme", "Crepe", "Crepom", "Criação", "Criativo", "Criptografia",
  "Criptomoeda", "Críquete", "Cristais", "Cristal", "Cristiano Ronaldo", "Croácia", "Crochê", "Crocodilo", "Crossover", "Cruel",
  "Crush", "Cruzamento", "Cruzeiro", "Cuba", "Cubo", "Cueca", "Cuiabá", "Cuidado", "Culinária", "Culpa",
  "Cultivo", "Cúmplice", "Cunhada", "Cunhado", "Cupuaçu", "Curativo", "Curau", "Curiosidade", "Curitiba", "Curral",
  "Curta", "da", "Daca", "Dacar", "Dachshund", "Dado", "dados", "Dalai Lama", "Dálmata", "Dama",
  "Damas", "Damasco", "Dança", "Danificado", "Dante Alighieri", "Darth Vader", "Datilografar", "DC", "de", "De",
  "Débito", "Decepção", "Decote", "Dedão", "Dedo", "Defensor", "Delegacia", "Delegado", "Délhi", "Dell",
  "delta", "Delta", "Demônio", "Denso", "Dental", "Dente", "Dentes", "Dentista", "Depósito", "Deprimido",
  "Derme", "Desânimo", "Descarga", "Desconfiança", "Desconforto", "Desejo", "Desenho", "Desenvolvedor", "Deserto", "Desespero",
  "Designer", "Desinfetante", "Deslizamento", "Desodorante", "Despacho", "Despensa", "Destino", "Destrancado", "Destruição", "Detergente",
  "Determinação", "Detetive", "Dethrone", "Dever", "Dharma", "Dia", "Dia das Mães", "Dia dos Namorados", "Dia dos Pais", "Diabetes",
  "Diafragma", "Diamante", "Dimensão", "Dinamarca", "Dinheiro", "Dior", "Diova", "Dique", "Direito", "Diretor",
  "Dirigível", "Discman", "discos", "Disney", "Dispositivo", "Disquete", "Distanciamento", "Distribuidor", "Distrito", "Dívida",
  "Divórcio", "Djibouti", "DNA", "do", "Doberman", "Dobrado", "Dobradura", "Doce", "Documentário", "Documento",
  "Dodgers", "Doente", "Dojô", "Dólar", "Dom Pedro", "Domador", "Dominica", "Dominó", "Doninha", "Dor",
  "Dormitório", "Dorso", "Dourado", "Dove", "Download", "Drácula", "Dragão", "Drama", "Drive", "Drone",
  "Druida", "Dubai", "Dublê", "Dublin", "Ducati", "Dumbledore", "Dungeon", "Dunk", "Dupla", "Durex",
  "duro", "Duro", "Dúvida", "DVD", "Eclair", "Eclipse", "Eco", "Economista", "Ecossistema", "Edição",
  "Edifício", "Educador", "Efêmero", "Egito", "Ego", "Egoísta", "El Salvador", "Elastano", "Elástica", "Elástico",
  "Elefante", "elétrica", "Eletricista", "elétrico", "Elétron", "Eletrônica", "Elevador", "Elfo", "Elixir", "Elon Musk",
  "Elvis Presley", "em", "Email", "Emirados Árabes", "Emmy", "Emoji", "Empate", "Empatia", "Empilhadeira", "Empregado",
  "Empresa", "Empréstimo", "Encanador", "Encanto", "Encharcado", "Enchente", "Energia", "Enfermeiro", "Enferrujado", "Engenheiro",
  "Engolidor", "Enguia", "Enteada", "Enteado", "Entrada", "Entregador", "Entusiasmo", "Envelope", "Enxada", "Enxaguante",
  "Enxaqueca", "Enxofre", "Epiderme", "Equador", "Equilíbrio", "Equilibrista", "Equipamento", "Eritreia", "Erupção", "Ervilha",
  "Escada", "Escala", "Escalada", "Escama", "Escápula", "Escarlate", "Escavadeira", "Escola", "Escolha", "Escorpião",
  "Escorredor", "Escova", "Escrita", "Escritório", "Escrivão", "Escudo", "Escultura", "Escuna", "escuro", "Escuro",
  "Esgrima", "Eslováquia", "Eslovênia", "Esmalte", "Esmeralda", "Esôfago", "espacial", "Espaçonave", "espada", "Espada",
  "Espadas", "Espanador", "Espanha", "Espantalho", "Espátula", "Espectro", "Espelho", "Esperança", "Esperto", "Espetáculo",
  "Espinafre", "Espiritismo", "Espírito", "espirra", "Esponja", "Esportivo", "Esposa", "Espremedor", "Espuma", "Espumante",
  "Esquadro", "Esqueleto", "Esqui", "Esquilo", "Essência", "Estábulo", "Estação", "Estacionamento", "Estádio", "Estado",
  "Estados Unidos", "Estadual", "Estanho", "Estante", "estar", "Estatística", "Estável", "Esteira", "Esterno", "Estiagem",
  "Estilete", "Estilingue", "Estocolmo", "Estômago", "Estônia", "Estrada", "Estranho", "Estreia", "Estrela", "Estressado",
  "Estuário", "Estúdio", "Éter", "Eternidade", "Ethereum", "Ética", "Etiópia", "Etiqueta", "Eucalipto", "Euforia",
  "Eufórico", "Euro", "Evolução", "Ex", "Exaustão", "Excentricidade", "Existência", "Exposição", "Expresso", "Externo",
  "Extrator", "Extrovertido", "Fábrica", "Faca", "Facão", "Facas", "Face", "Facebook", "Fada", "Fada do Dente",
  "Faixa", "falante", "Falcão", "Falso", "Família", "Fantasia", "Fantasma", "Fantoche", "Farda", "Farinha",
  "Farmacêutico", "Farmácia", "Faroeste", "Farpado", "Fascínio", "Faustão", "Fax", "Fazenda", "Fé", "Febre",
  "Fechado", "Fechadura", "Feijão", "Feio", "Feira", "Feiticeiro", "Feitiço", "Feliz", "Fêmur", "fenda",
  "Fênix", "Feriado", "Férias", "Ferida", "Fernando Pessoa", "Ferradura", "Ferramenta", "Ferrari", "Ferro", "Ferrorama",
  "Ferrugem", "Festa", "Festival", "Fiat", "Fibra", "Fíbula", "Ficção", "Ficha", "Fichário", "Fidel Castro",
  "Fígado", "Figueirense", "Fiji", "Filha", "Filho", "Filiação", "Filipinas", "Filmagem", "Filósofo", "Filtro",
  "Fim", "Finalização", "Financeiro", "Financiamento", "Finlândia", "Fio", "Firewall", "Fiscal", "Física", "Fisioterapeuta",
  "fita", "Fita", "Fivela", "Fixo", "Flamenco", "Flamengo", "Flanela", "Flash", "Flauta", "Flautim",
  "Flecha", "Flexível", "Flor", "Floresta", "Florianópolis", "Fluminense", "Flúor", "Fobia", "Foca", "Fogão",
  "Fogueira", "Foguete", "Foice", "Folha", "Folículo", "Folk", "Fone", "Ford", "Formão", "Formatura",
  "Formiga", "Fornecedor", "Forno", "Forró", "Fortaleza", "Forte", "Fósforo", "Fotografia", "Fraco", "Frágil",
  "Fralda", "França", "Franco", "Frango", "Frankenstein", "Fratura", "Fred", "Freezer", "Fresadora", "Fresco",
  "Freya", "Frigideira", "Frio", "Frodo", "Fronteira", "Frustração", "Frutas", "Fúcsia", "Fungo", "Funicular",
  "Funk", "Furacão", "Furadeira", "futebol", "Futebol", "Futsal", "Gabão", "Gabarito", "Gaita", "Gaivota",
  "Galho", "Galinha", "Galinheiro", "Galo", "Galpão", "Gamão", "Gâmbia", "Game", "Gamer", "Gana",
  "Gandalf", "Gandhi", "Ganso", "Garagem", "Garapa", "Garçom", "Garfo", "Garganta", "Garoto", "Garoupa",
  "Garra", "Garrafa", "gás", "Gasoso", "Gastão", "Gastrite", "Gato", "Geada", "Gel", "Geladeira",
  "Gelado", "Gelatina", "Geleia", "gelo", "Gelo", "Gêmeos", "Generoso", "Genética", "Gengibre", "Gengis Khan",
  "Gengiva", "Gengivite", "Genro", "Gentil", "Geógrafo", "Geometria", "Geórgia", "Gerador", "Gérbera", "Gergelim",
  "Gesso", "Gestor", "Giants", "Gif", "Gigabyte", "Gigante", "Gin", "Ginásio", "Girafa", "Girassol",
  "Giz", "Glândula", "Globo", "Glóbulo", "Glúteo", "Goblin", "Gohan", "Goiabada", "Goiânia", "Goiás",
  "Goku", "Gola", "Golden", "Golfe", "Golfinho", "Gollum", "Google", "Google Home", "GoPro", "Gordo",
  "Gospel", "Grafite", "Grammy", "Grampeador", "Grampo", "Granada", "Grande", "Grandes", "Granito", "Granizo",
  "Grão", "Gratidão", "Gravata", "Gravidade", "Grécia", "Grêmio", "Greyhound", "Grifo", "Grimório", "Gripe",
  "Grogue", "Guache", "Guarani", "Guarda", "Guarulhos", "Guatemala", "Gucci", "Gude", "Guerra", "Guerreiro",
  "Gugu", "Guiana", "Guincho", "Guindaste", "Guiné", "Guioza", "Guitarra", "Haas", "Hacker", "Haiti",
  "Hall", "Halloween", "Hambúrguer", "Hamilton", "Hamster", "Handebol", "Hanoi", "Harley-Davidson", "Harmonia", "Harpa",
  "Harry Potter", "Harumaki", "Hashi", "Hashtag", "Hatch", "Havaianas", "Havana", "HD", "HDMI", "Heat",
  "Hela", "Helicóptero", "Hélio", "Helsinque", "Hematoma", "Hera", "Hércules", "Hering", "Hermes", "Hermione",
  "Herói", "Hibisco", "híbrido", "Hidra", "Hidratante", "Hidroavião", "Hidrocor", "Hidrogênio", "Hidromel", "Higiênico",
  "Himalaia", "Hip Hop", "Hipertensão", "Hipopótamo", "Historiador", "Hitchcock", "Hitler", "Holanda", "Homem", "Homem de Ferro",
  "Homem-Aranha", "Homer Simpson", "Homero", "Honda", "Honduras", "Hong Kong", "Hóquei", "Horizonte", "Hormônio", "Horóscopo",
  "Horta", "Hortelã", "Hortênsia", "Horticultura", "hóspedes", "Hospital", "Hossomaki", "Hot", "Hot Wheels", "Hotel",
  "House", "Hoverboard", "HP", "Hulk", "Humilhação", "Hungria", "Husky", "Iate", "Identidade", "Idiossincrasia",
  "Idoso", "Iêmen", "Iene", "Ignorante", "Igreja", "Iguana", "Ilha", "Ilusão", "Ilustração", "Ilustrador",
  "Imagem", "Imobiliário", "Império", "Impermeabilizante", "Imposto", "Impressão", "Impressora", "Incensos", "Inconstitucionalissimamente", "Índia",
  "Indicador", "Indie", "Índigo", "Indonésia", "Indústria", "industrial", "Inexorável", "infantil", "Infecção", "Inferno",
  "Infinito", "Inflação", "Inflamação", "Influencer", "Ingênuo", "inglesa", "Ingresso", "Inimigo", "Inimizade", "Injeção",
  "Injustiça", "Inocência", "Inseticida", "Insosso", "Instagram", "Instável", "Instrumentista", "Instrumento", "Instrutor", "Integral",
  "Inteiro", "Intel", "Inteligência", "Inteligente", "Intenção", "Inter de Milão", "Interesse", "Interface", "Internacional", "Internet",
  "Intérprete", "Interruptor", "Intestino", "íntima", "Intranet", "Introvertido", "Inundação", "Inveja", "Inversora", "Investimento",
  "Iogurte", "Ioiô", "IPA", "Ipê", "iPod", "Ira", "Irã", "Iraque", "íris", "Íris",
  "Irlanda", "Irmã", "Irmandade", "Irmão", "Irritação", "Isaac Newton", "Islamabad", "Islândia", "Isolante", "Israel",
  "Istambul", "Itália", "Itaú", "Iveco", "Ivete Sangalo", "J.K. Rowling", "Jacaré", "Jacarta", "Jade", "Jaguar",
  "Jamaica", "James Bond", "Janela", "jantar", "Japão", "Japonês", "Japonesa", "Jaqueta", "Jardim", "Jardinagem",
  "Jasmim", "Jato", "Javali", "Jazz", "Jeans", "Jeff Bezos", "Jerry", "Jerusalém", "Jesus", "Jinx",
  "Jipe", "jitsu", "Jiu", "Joana d'Arc", "Joanesburgo", "Joaninha", "João Pessoa", "Joe", "Joelheira", "Joelho",
  "Jogador", "Jogo", "jogos", "Jogos", "Jordânia", "Jorge Amado", "Jovem", "Judô", "Juiz", "Julieta",
  "Júlio César", "Junina", "Juros", "Justiça", "Juventus", "K-Pop", "Kani", "Karma", "Katmandu", "Kawasaki",
  "Ken", "Kennedy", "Ketchup", "Kiev", "Kinshasa", "Kitesurf", "Kiwi", "Knicks", "Kraken", "Kratos",
  "Kuala Lumpur", "Kuwait", "Lã", "La Paz", "Lábio", "Labirinto", "Laboratório", "Labrador", "Laço", "Lacta",
  "Ladino", "Lady Gaga", "Lagarto", "Lager", "Lago", "Lagoa", "Lagos", "Lagosta", "Lagostim", "Laje",
  "Lakers", "Lambari", "Lamborghini", "Lamen", "Lâmina", "Lâmpada", "Lançamento", "Lancha", "Land Rover", "Laos",
  "Lápis", "Lapiseira", "Laranja", "Laringe", "Las Vegas", "lata", "Latão", "Latina", "Lava", "Lavabo",
  "Lavanda", "Lavanderia", "Lavoura", "lazúli", "Leal", "leão", "Leão", "Legging", "Lego", "Legolas",
  "leite", "Leite", "Leiteira", "Leitura", "Lêmure", "Lenço", "Lenin", "Lenovo", "Lente", "Lentilha",
  "Lento", "Leonardo da Vinci", "Leopardo", "Lesoto", "Letônia", "Letra", "Leve", "Leviatã", "LG", "Líbano",
  "Liberdade", "Libéria", "Libertadores", "Líbia", "Libra", "Libreville", "Lich", "Licor", "Líder", "Liechtenstein",
  "Ligamento", "Like", "Lilás", "Lima", "Limão", "Limpo", "Limusine", "Lincoln", "Língua", "Linguado",
  "Linguiça", "Linho", "Link", "Liquidificador", "Líquido", "Lira", "Lírio", "Lisa", "Lisboa", "Liso",
  "Lítio", "Lituânia", "Liverpool", "livre", "Livro", "Lixa", "Lixadeira", "Lixeira", "Lobisomem", "Lobo",
  "Lóbulo", "Locomotiva", "Login", "Loja", "Loki", "Lombar", "Lona", "Londres", "Longa", "Lontra",
  "Los Angeles", "Lotus", "Lótus", "Louis Vuitton", "Lousa", "Lua", "Luanda", "Luau", "Lúcifer", "Ludo",
  "Luffy", "Luigi", "Luke Skywalker", "Lula", "Lula Molusco", "Lulu", "Lustra", "Luta", "Luva", "Luvas",
  "Luxação", "Luxemburgo", "Luz", "Lyon", "Maçã", "Macacão", "Macaco", "Macapá", "Macarrão", "Macedônia",
  "Maceió", "Machado", "Machado de Assis", "Maciço", "Macio", "Madagascar", "Madeira", "Madonna", "Madrasta", "Madre Teresa",
  "Madri", "Madrinha", "Mãe", "Maestro", "Magenta", "Magia", "Mágico", "Magnésio", "Mago", "Magro",
  "Maine", "Maiô", "Maionese", "Mal", "Mala", "Malabarista", "Malaquita", "Malásia", "Malaui", "Maldição",
  "Maldivas", "Maldoso", "Malha", "Malho", "Mali", "Malicioso", "Malta", "Maltês", "Mamão", "Mamona",
  "Mana", "Manaus", "Manchester City", "Manchester United", "Mandíbula", "Manga", "Mangue", "Manila", "Manjar", "Manjericão",
  "Manjerona", "Manteiga", "Mão", "Maomé", "Mapa", "Maputo", "Maquiagem", "Máquina", "mar", "Mar",
  "Maradona", "Maratona", "Marca", "Marcenaria", "Marceneiro", "Maremoto", "Margarida", "Margarita", "Marge", "Maria",
  "Marido", "Marilyn Monroe", "Marimba", "marinha", "Marinha", "marinho", "Marinho", "Mario", "Marionete", "Marisco",
  "Mark Zuckerberg", "mármore", "Mármore", "Marreta", "Marrocos", "Marrom", "Marseille", "Martelo", "Martin Luther King", "Martini",
  "Marvel", "Máscara", "Maserati", "Masmorra", "Massa", "Massinha", "Master Chief", "Mastercard", "Mastiff", "Mata",
  "Match", "Mate", "Matemática", "Maternidade", "Maurício", "Mauritânia", "McDonald's", "McLaren", "MDF", "Mecânico",
  "Mecanismo", "Médico", "Médio", "Meditação", "Medo", "Medroso", "Medula", "Medusa", "Meia", "Mel",
  "Melancia", "Melancolia", "Melão", "Melbourne", "Melissa", "Melodia", "Meme", "Memória", "Meninge", "Menisco",
  "Menstrual", "Mentira", "Mentor", "Mercado", "Mercedes", "Mercúrio", "Merendeiro", "Mergulho", "mesa", "Mesa",
  "Mesquita", "Messi", "Meteoro", "metragem", "Metrô", "México", "Mexilhão", "Miami", "Mianmar", "Michael Jackson",
  "Michelangelo", "Mickey", "Micro", "Microfibra", "Microfone", "Microondas", "Microsoft", "Milan", "Milho", "Mimico",
  "Mindinho", "Mineral", "Mini Cooper", "Miniaturas", "Minivan", "Minnie", "Minotauro", "Missoshiro", "Mithril", "Mixer",
  "MMA", "Mocaccino", "Moçambique", "Mochila", "Modelagem", "Moeda", "Moedas", "Mogadíscio", "Mogli", "Moinho",
  "Moisés", "Mojito", "Molar", "Moldávia", "Mole", "Molécula", "Moleque", "Moletom", "Molhado", "Molho",
  "Mônaco", "Monge", "Mongólia", "Monitor", "Monociclo", "Monomotor", "Monopoly", "Monotrilho", "Monstro", "Montanha",
  "Monteiro Lobato", "Montenegro", "Montevidéu", "Monumento", "MOP", "Moral", "Morango", "Morcego", "Moreia", "Morno",
  "Morsa", "Morte", "Morto", "Mosaico", "Moscou", "Mostarda", "Mosteiro", "Motivação", "Moto", "Motocicleta",
  "Motor", "Motorista", "Motorola", "Mountain", "Mouse", "Mousse", "móveis", "Móvel", "Mozart", "MP3",
  "MPB", "Muay", "Muleta", "Mulher Maravilha", "Multiuso", "Mumbai", "Múmia", "Músculo", "Museu", "Musgo",
  "Música", "Musical", "Mussolini", "na", "Nacional", "Nada", "Naftalina", "Naip", "Nairóbi", "Namíbia",
  "namorada", "namorado", "Namorado", "Napoleão", "Napoli", "Narina", "Nariz", "Naruto", "Nascente", "Nascimento",
  "Natação", "Natal", "Natura", "Náutico", "Navegador", "Navio", "Neblina", "Necessaire", "Necromante", "Negociador",
  "Negro", "Negroni", "Nelson Mandela", "Neon", "Nepal", "Nervo", "Nervoso", "Nestlé", "Neta", "Netflix",
  "Neto", "Neurônio", "Nêutron", "Nevasca", "neve", "Neve", "Nevoeiro", "Neymar", "Nicarágua", "Níger",
  "Nigéria", "Niguiri", "Nike", "Nikon", "Nintendo", "Níquel", "Nitrogênio", "Nivea", "Nível", "no",
  "Nocaute", "Noé", "Noite", "Noiva", "Noivado", "Noivo", "Nojo", "Noob", "Nora", "Nori",
  "Noruega", "Nostalgia", "Nota", "Notário", "Notebook", "Nova York", "Nova Zelândia", "Novo", "Noz", "Nozinhos",
  "Nubank", "Nuca", "Nunca", "Nutricionista", "Nuvem", "Nvidia", "Nylon", "Oásis", "Obama", "Obi-Wan",
  "Oboé", "Observação", "Observatório", "Obsidiana", "Oceano", "Oco", "Ocre", "Octógono", "Óculos", "Odin",
  "Ódio", "Oficina", "Oftalmologista", "Ogro", "Óleo", "Olho", "Oliva", "Omã", "Ombro", "Omo",
  "Onça", "ônibus", "Ônibus", "Ônix", "Opaco", "Opala", "Ópera", "operacional", "Operador", "Opressão",
  "Oral-B", "Orangotango", "Orbe", "Orc", "Ordem", "Orégano", "Orelha", "Organizado", "Órgão", "Orgulho",
  "Origami", "Orka Studio", "Orka Zoo", "Orquestra", "Orquídea", "Orvalho", "OSB", "Oscar", "Oslo", "Osso",
  "Ostra", "Otimismo", "Otorrinolaringologista", "Ottawa", "Ouriço", "Ouro", "Ouros", "Ova", "Ovário", "Ovelha",
  "Ovo", "Oxigênio", "Pá", "Pac-Man", "Paciência", "Packers", "Paçoca", "Pacu", "Padeiro", "Padrasto",
  "Padrinho", "Pager", "Pagode", "Pai", "Painel", "País", "Paixão", "Palácio", "Paladino", "Paleta",
  "palhaço", "Palhaço", "Palma", "Palmas", "Palmeiras", "Palmilha", "Pálpebra", "Pamonha", "Panamá", "Panasonic",
  "Pâncreas", "Panda", "Pandeiro", "Panela", "Panetone", "Pânico", "Panificação", "Pano", "Pântano", "Panturrilha",
  "Pão", "Papa Francisco", "Papagaio", "Papai Noel", "papão", "Papel", "papelão", "Papua Nova Guiné", "Paquistão", "Parafusadeira",
  "Parafuso", "Paraguai", "Paralelepípedo", "Parapente", "Paraquedas", "Parceira", "Parceiro", "Parceria", "Pardo", "Parente",
  "Pargo", "Paris", "Parque", "Páscoa", "Pasta", "Pasto", "Pastor", "Paternidade", "Pateta", "Patinete",
  "Patins", "Pato", "Pato Donald", "Patrick", "Patriots", "Pau", "Paulo Coelho", "Paus", "Pauzinhos", "Pavão",
  "Pavê", "Paysandu", "Paz", "Pé", "Peach", "Peça", "Pecado", "Pedagogo", "Pedra", "pedreiro",
  "Pedreiro", "Pedro Álvares Cabral", "Pégaso", "Peito", "Peixe", "Peixeiro", "Peixes", "Pele", "Pelé", "Pelve",
  "Pen", "Peñarol", "Pente", "Pentear", "Pepino", "Pepsi", "Pequeno", "Pequim", "Pera", "Perdão",
  "Perdedor", "Perdigão", "Perfil", "Perfume", "Perfurador", "Perfuratriz", "Pergaminho", "Perito", "Perna", "Pérola",
  "Persa", "Perspicácia", "Peru", "Perua", "Peruca", "Pesadelo", "Pesado", "Pescoço", "Peso", "Pesquisador",
  "Pêssego", "Pessimismo", "Peteca", "petroleiro", "Petúnia", "Philips", "Pia", "Piano", "Pião", "Pica-Pau",
  "Picadeiro", "Picante", "Picape", "Picareta", "Picasso", "Pife", "Pijama", "Pikachu", "Pilar", "Piloto",
  "Pilsen", "Pimenta", "Pimentão", "Piña", "Pinça", "Pincel", "pingue", "Pinguim", "Pinheiro", "Pinscher",
  "Pintado", "Pintor", "Pintura", "Pipa", "Pipoca", "Piquenique", "Piranha", "Pirarucu", "Piscina", "Pista",
  "Pit", "Pitbull", "Pix", "Pixel", "Pizza", "Plaina", "Plainadeira", "Planador", "Planeta", "Planetário",
  "Planície", "Planilha", "Planner", "Planta", "Plantação", "Plaqueta", "Plasma", "Plástico", "Plataforma", "Platina",
  "Playmobil", "PlayStation", "Pluto", "Plutônio", "Pneumonia", "Pó", "Pobre", "Poção", "Pochete", "Poço",
  "Point", "Poke", "Pole", "Polegar", "Policial", "Polido", "Poliéster", "Politriz", "Polo", "Polônia",
  "Polvo", "Pomada", "Pomar", "Pomba", "Pombo", "Pomerânia", "Poncho", "pongue", "Ponte", "Ponte Preta",
  "Poodle", "Pop", "Pôquer", "Porão", "Porcelanato", "Porco", "Poros", "Poroso", "Porsche", "Porta",
  "Portal", "Porteira", "Porto", "Porto Alegre", "Porto Velho", "Portugal", "Pós", "Poseidon", "Position", "Post",
  "Post-it", "Posto", "Potássio", "Pote", "Poupança", "Pousada", "Praça", "Prada", "Praga", "Praia",
  "Prancheta", "Prata", "Prateleira", "Prato", "Prazer", "Prédio", "Prefeitura", "Prego", "Preguiçoso", "Prensa",
  "pressão", "Pressão", "Presunto", "Preta", "Pretendente", "Preto", "Pretória", "Prima", "Primavera", "Primo",
  "Princesa Diana", "Privacidade", "Privada", "Pro", "Proativo", "Processador", "Procrastinação", "Procurador", "Produtor", "Profecia",
  "Professor", "Programa", "Programação", "Programador", "Projetor", "Promotor", "Propósito", "Próstata", "Proteção", "Protetor",
  "Próton", "Província", "PSG", "Psicólogo", "PSV", "Pudim", "Pug", "Pulmão", "Pulôver", "Pulseira",
  "Pulso", "Puma", "Punção", "Punho", "Pupila", "Putin", "PVC", "Quadra", "Quadriciclo", "Quadril",
  "Quadro", "Quartel", "Quarterback", "Quarto", "Quartzo", "que", "Quebra", "Quebrado", "Queijo", "Queixo",
  "Quênia", "Quente", "Querubim", "Quest", "Quimera", "Química", "Quimono", "Quindim", "Quirguistão", "Quito",
  "R&B", "Rã", "Rabanada", "Rachado", "Racional", "Rádio", "Ragdoll", "Raia", "Rainha Elizabeth", "Raio",
  "Raiva", "Raiz", "Ralo", "Rancho", "Rancor", "Ranger", "Rap", "Rapadura", "Rápido", "Raposa",
  "Raquete", "Raspador", "Rato", "Rave", "Real", "Real Madrid", "Reator", "Reboco", "Recepcionista", "Recibo",
  "Recife", "reco", "Reco", "Recorte", "Red Bull", "Red Sox", "Rede", "Rédea", "Redenção", "Reels",
  "Reencarnação", "Refrão", "Refrigerante", "Regata", "Reggae", "Reggaeton", "régia", "Região", "Régua", "Rei",
  "Rei Arthur", "Reino", "Reino Unido", "Rejeição", "Relâmpago", "Relatividade", "Relatório", "Relíquia", "Relógio", "Remo",
  "Remorso", "Removedor", "Renault", "Renda", "Renner", "Renovação", "Repelente", "Representante", "República Checa", "Requeijão",
  "Resfriado", "Resiliência", "Resina", "Resistente", "Resolução", "Respeito", "Responsabilidade", "Ressentimento", "Resta", "Restaurante",
  "Retina", "Retriever", "Retroescavadeira", "reuniões", "Réveillon", "Revestimento", "Riachuelo", "Riad", "Rico", "Rígido",
  "Rihanna", "Rim", "Rinoceronte", "Rio", "Rio Branco", "Rio de Janeiro", "Risada", "Ritmo", "Rivalidade", "River Plate",
  "RNA", "Robalo", "Robata", "Roberto Carlos", "Robô", "Rocha", "Rock", "Rodada", "rodas", "Rodízio",
  "Rodo", "Rodovia", "Rodoviário", "Rolex", "Rolinho", "Roll", "Rolls-Royce", "Rolo", "Roma", "Romance",
  "Romênia", "Romeu", "Rony", "Roosevelt", "Rosa", "Rosário", "Rosé", "Rosto", "Rotatória", "Roteiro",
  "Rottweiler", "Roupa", "Roupão", "Roxo", "Royal", "Royal Enfield", "RPG", "Rua", "Ruanda", "Rubi",
  "Rublo", "Rugby", "Rugoso", "Rum", "Runas", "Rúpia", "Ruptura", "Rússia", "Ryu", "Sabão",
  "Sábio", "Sabonete", "Sacada", "Saco", "Sadia", "Safira", "Sagitário", "Sagu", "Saia", "Saída",
  "Sal", "Sala", "Salada", "Salário", "Salgado", "Salmão", "Salsa", "Salsicha", "Salto", "Salvador",
  "Salvador Dalí", "Sálvia", "Samambaia", "Samba", "Samoa", "Samsung", "San Marino", "Sandália", "Sanduicheira", "Sanfona",
  "Sangue", "Sanitária", "Sanitário", "Santa Cruz", "Santa Lúcia", "Santiago", "Santo", "Santos", "Santuário", "São",
  "São Francisco", "São João", "São Luís", "São Paulo", "São Tomé e Príncipe", "Sapateado", "Sapatilha", "Sapato", "Sapatos", "Sapo",
  "Saquê", "Sardinha", "Sargento", "Sarja", "Sashimi", "Sasuke", "Satanás", "Satélite", "Sátira", "Satisfação",
  "Saudade", "Saudável", "Sauron", "Savanas", "Saxofone", "Scania", "Schumacher", "Scooby-Doo", "Scooter", "Scorpion",
  "Scorsese", "Script", "Seara", "Seca", "Secador", "Seco", "Seda", "Sedã", "Seguidor", "Segurança",
  "Sela", "Selador", "Seleção Alemã", "Seleção Argentina", "Seleção Brasileira", "Seleção Francesa", "Seleção Italiana", "Selos", "Selva", "Semente",
  "Sempiterno", "Sempre", "Senegal", "Senha", "Senna", "Sensor", "Sentido", "Separação", "Septo", "Serafim",
  "Sereia", "Serendipidade", "Serenidade", "Serpente", "serra", "Serra", "Serra Leoa", "Serrote", "Sertanejo", "Sérvia",
  "serviço", "Servidor", "Set", "Seul", "Sevilla", "Shakespeare", "Shakira", "Shampoo", "Sherlock Holmes", "Shih",
  "Shimeji", "Shitake", "Shopping", "Shorts", "Show", "Shoyu", "Siamês", "Siberiano", "Sifão", "Sigilo",
  "Silêncio", "Silício", "Silo", "Silvio Santos", "Simulação", "Sinagoga", "Sinal", "Sinapse", "Sincero", "Singapura",
  "Siri", "Síria", "Siso", "Sistema", "Sitar", "Site", "Sítio", "Skate", "Slide", "Slime",
  "Smartphone", "Smartwatch", "Snowboard", "Sobrado", "Sobrancelha", "Sobretudo", "Sobrinha", "Sobrinho", "Social", "Sócio",
  "Socorrista", "Sódio", "Sofá", "Softbol", "Software", "Sogra", "Sogro", "Soja", "Sol", "Sola",
  "Solar", "Soldador", "Soldadora", "Solidão", "Solidariedade", "Sólido", "Solo", "Som", "Somália", "Sombra",
  "Sombras", "Sommelier", "Sonho", "Sonic", "Sony", "Sorte", "Sorvete", "Sótão", "Soul", "Sovaco",
  "Spam", "Spaniel", "Sphynx", "Spoiler", "Sport", "Sporting", "Spotify", "Sri Lanka", "Stalin", "Stan Lee",
  "Steve Jobs", "Steven Spielberg", "Sticker", "Stop", "Story", "Stout", "Streamer", "Streaming", "Suazilândia", "Sub-Zero",
  "Submarino", "Subúrbio", "Suco", "Suculenta", "Sudão", "Sudare", "Sudoku", "Suécia", "Suéter", "Suíça",
  "Suíte", "Sujo", "Sulfite", "Sunga", "Superman", "Supernova", "Surf", "Suricato", "Suriname", "Surpresa",
  "Sushi", "Suspensa", "Suspense", "Suspiro", "Susto", "Sutiã", "SUV", "Suva", "Suzuki", "Sydney",
  "Tablet", "Tábua", "Tabuleiro", "Taco", "Taekwondo", "Taiga", "Tailândia", "Tails", "Tainha", "Taipei",
  "Taiwan", "Tajiquistão", "Talco", "Talhadeira", "Talher", "Talismã", "Tambaqui", "Tambor", "Tango", "Tanque",
  "Tanzânia", "Tapete", "Tapioca", "Tarantino", "Tarê", "Tarô", "Tartaruga", "Tarzan", "Tatame", "Taverna",
  "Taxista", "Teatro", "Techno", "Teclado", "técnica", "Técnico", "Tecnologia", "Tédio", "Teerã", "Teimoso",
  "Tela", "Teleférico", "Telefone", "Telescópio", "Televisão", "Telha", "Temaki", "Temor", "Tempestade", "Templo",
  "Tempo", "Tempurá", "Tendão", "tênis", "Tênis", "Tensão", "Teppan", "Tequila", "Terapeuta", "Tereré",
  "Teresina", "Teriyaki", "Terminal", "Terno", "Terra", "Terraço", "Terreiro", "Terremoto", "Terror", "Tesla",
  "Tesoura", "Tesoureiro", "Tesouro", "Testa", "Testemunha", "texto", "Texugo", "thai", "Thanos", "Thor",
  "Tia", "Tíbia", "Tie", "Tigre", "Tijolo", "TikTok", "Tilápia", "Timidez", "Tímido", "Timor-Leste",
  "Tímpano", "Tinta", "Tinteiro", "Tio", "Tiradentes", "Tireoide", "Titã", "Titânio", "Toalha", "Toca",
  "Tofu", "Togo", "Tolerância", "Tom", "Tomada", "Tomate", "Tommy Hilfiger", "Tonga", "Topázio", "Tóquio",
  "Torá", "Tórax", "Torção", "Tornado", "Torneira", "Torneiro", "Torno", "Tornozelo", "Torradeira", "Torre",
  "Torresmo", "Torta", "Tosse", "Totalidade", "Tottenham", "Touca", "Touchdown", "Touro", "Toyota", "Tragédia",
  "Traidor", "Trailer", "Trampolim", "Trancado", "Trance", "Transatlântico", "Transferidor", "Transformador", "Translúcido", "Transparente",
  "Trap", "Trapézio", "Trapezista", "Traqueia", "Trator", "Trave", "Travesseiro", "Trem", "Trena", "Trend",
  "Trenó", "Trevas", "Trevo", "Tribunal", "Triciclo", "Tricô", "Trigo", "Trilha", "Trinidad e Tobago", "Tripofobia",
  "Trípoli", "Triste", "Tristeza", "Triumph", "Troll", "Trombone", "Trompa", "Trompete", "Tronco", "Trono",
  "Tropeiro", "Trovão", "Truco", "Trufa", "Trump", "Truque", "Truta", "Tsunami", "Tuba", "Tubarão",
  "Tudo", "Tufão", "Tule", "Tulipa", "Tumba", "Tundra", "Túnel", "Tunísia", "Turbina", "Turcomenistão",
  "Turno", "Turquesa", "Turquia", "Tutela", "Tutor", "Tuvalu", "Twitter", "Tyson", "Tzu", "Uber",
  "Ucrânia", "Udon", "UFC", "Uganda", "Ukulele", "Úlcera", "Ulna", "Um", "Umbigo", "Umedecido",
  "Úmero", "Úmido", "Unha", "União", "Unicórnio", "Uniforme", "Universidade", "Uno", "Upload", "Uramaki",
  "Urânio", "Urbanista", "URL", "Urso", "Uruguai", "Usado", "USB", "Útero", "Utilitário", "Uva",
  "Uzbequistão", "Vaca", "Vacina", "Vagão", "Vaidade", "Vale", "Valencia", "Valete", "Valores", "Valsa",
  "Válvula", "Vampiro", "Van", "Van Gogh", "Vanuatu", "Varanda", "Varinha", "Varsóvia", "Vasco", "Vaso",
  "Vassoura", "Vaticano", "Vazamento", "Vazio", "Veado", "Vedas", "Vegeta", "Veia", "Veja", "Veleiro",
  "Velho", "Veludo", "Vencedor", "Vendedor", "Venezuela", "Ventilador", "Vento", "Ventoinha", "Ventre", "Ventrículo",
  "Verdade", "Verde", "Vergalhão", "Vergonha", "Vermelha", "Vermelho", "Verniz", "Versace", "Verso", "Vesícula",
  "Vestido", "Veterinário", "Viaduto", "Viagem", "Viatura", "Vibração", "Vida", "Vidente", "Videocassete", "Videogame",
  "Vidro", "Vieira", "Viena", "Vietnã", "Viga", "Vila", "Vila Nova", "Vinagre", "Vinho", "Vinil",
  "Viola", "Violão", "Violeta", "Violino", "Violoncelo", "Vira", "Viral", "Virgem", "Virilha", "Virtual",
  "Virtude", "Vírus", "Visa", "Viscose", "Vitória", "viva", "Viveiro", "Vivo", "Vizinho", "Vodka",
  "Voldemort", "Vôlei", "Volkswagen", "Volume", "Volvo", "Vôngole", "Vontade", "Vórtice", "Voz", "VR",
  "Vulcão", "Vulto", "Walkman", "Walt Disney", "War", "Warren Buffett", "Warriors", "Wasabi", "Washington", "Watson",
  "Weiss", "Wellington", "Whisky", "Wi-Fi", "Williams", "Windsurf", "Wok", "Xadrez", "Xangai", "Xarope",
  "Xbox", "Xiaomi", "Xícara", "Xilofone", "Xuxa", "Yakisoba", "Yamaha", "Yankees", "Yoda", "Yoga",
  "Yorkshire", "YouTube", "Youtuber", "Yuan", "Zâmbia", "Zara", "Zebra", "Zelda", "Zeus", "Zimbábue",
  "Zinco", "Zíper", "Zoológico", "Zumba", "Zumbi"
];

export const palavrasEN = [
    //1. Objetos do cotidiano
    "Chair", "Table", "Sofa", "Bed", "Pillow", "Blanket", "Cushion", "Wardrobe", "Shelf", "Bookcase",
    "Door", "Window", "Curtain", "Rug", "Mirror", "Lamp", "Switch", "Outlet", "Fan", "Heater",
    "Refrigerator", "Freezer", "Stove", "Oven", "Microwave", "Pan", "Frying pan", "Plate", "Glass", "Cup",
    "Cutlery", "Knife", "Fork", "Spoon", "Board", "Blender", "Mixer", "Coffee maker", "Bottle", "Container",
    "Brush", "Comb", "Soap", "Shampoo", "Towel", "Paper", "Notebook", "Book", "Pen", "Pencil",
    "Eraser", "Sharpener", "Backpack", "Bag", "Wallet", "Key", "Lock", "Watch", "Cellphone", "Telephone",
    "Computer", "Keyboard", "Mouse", "Monitor", "Printer", "Charger", "Headphones", "Box", "Remote", "Television",
    "Radio", "Camera", "Glasses", "Umbrella", "Cap", "Hat", "Shirt", "Pants", "Shoes", "Socks",
    "Belt", "Coat", "Jacket", "Ladder", "Hammer", "Screwdriver", "Pliers", "Broom", "Mop", "Bucket",
    "Shovel", "Trash can", "Bag", "Cardboard box", "Tape", "Scissors", "Glue", "Envelope", "Calendar", "Planner",
    //2. Comida
    "Rice", "Beans", "Meat", "Chicken", "Fish", "Egg", "Bread", "Milk", "Cheese", "Butter",
    "Sugar", "Salt", "Oil", "Olive Oil", "Pasta", "Pizza", "Hamburger", "Sausage", "Ham", "Bacon",
    "Lettuce", "Tomato", "Carrot", "Potato", "Onion", "Garlic", "Broccoli", "Cabbage", "Spinach", "Corn",
    "Peas", "Brown Rice", "Black Beans", "Lentils", "Chickpeas", "Soy", "Mushroom", "Pumpkin", "Zucchini", "Eggplant",
    "Cucumber", "Bell Pepper", "Apple", "Banana", "Orange", "Grape", "Mango", "Strawberry", "Pineapple", "Lemon",
    "Watermelon", "Melon", "Pear", "Papaya", "Kiwi", "Nuts", "Peanuts", "Walnuts", "Almonds", "Yogurt",
    "Cream Cheese", "Cream", "Ice Cream", "Cake", "Pie", "Cookie", "Biscuit", "Chocolate", "Candy", "Honey",
    "Jam", "Pudding", "Mousse", "Cereal", "Oats", "Flour", "Wheat", "Green Corn", "Coffee", "Tea",
    "Juice", "Soda", "Water", "Wine", "Beer", "Sauce", "Ketchup", "Mustard", "Mayonnaise", "Vinegar",
    "Pepper", "Oregano", "Basil", "Cinnamon", "Dark Chocolate", "Condensed Milk", "Heavy Cream", "Rice Pudding", "Cheese Bread", "Chocolate Cake",
    //3. Profissões
    "Doctor", "Nurse", "Dentist", "Veterinarian", "Pharmacist", "Psychologist", "Physiotherapist", "Nutritionist", "Therapist", "Paramedic",
    "Teacher", "Educator", "Pedagogue", "Tutor", "Instructor", "Researcher", "Scientist", "Historian", "Geographer", "Philosopher",
    "Engineer", "Architect", "Urban Planner", "Designer", "Illustrator", "Animator", "Programmer", "Developer", "Analyst", "Technician",
    "Electrician", "Plumber", "Bricklayer", "Carpenter", "Woodworker", "Painter", "Welder", "Mechanic", "Machinist", "Operator",
    "Driver", "Pilot", "Conductor", "Delivery Worker", "Mail Carrier", "Truck Driver", "Taxi Driver", "Navigator", "Commander", "Captain",
    "Lawyer", "Judge", "Prosecutor", "Detective", "Forensic Expert", "Clerk", "Defender", "Attorney", "Notary", "Auditor",
    "Accountant", "Economist", "Administrator", "Manager", "Consultant", "Broker", "Appraiser", "Banker", "Treasurer", "Financial Analyst",
    "Salesperson", "Attendant", "Cashier", "Shop Assistant", "Receptionist", "Merchant", "Representative", "Negotiator", "Distributor", "Buyer",
    "Cook", "Chef", "Baker", "Pastry Chef", "Butcher", "Fishmonger", "Caterer", "Waiter", "Bartender", "Sommelier",
    //4. Natureza
    "Tree", "Forest", "Jungle", "Woods", "Grove", "Field", "Plain", "Mountain", "Range", "Hill",
    "Valley", "Desert", "Oasis", "Beach", "Coast", "Island", "Archipelago", "Ocean", "Sea", "Lake",
    "Lagoon", "River", "Stream", "Waterfall", "Spring", "Delta", "Estuary", "Swamp", "Marsh", "Mangrove",
    "Snow", "Ice", "Hail", "Rain", "Storm", "Wind", "Breeze", "Hurricane", "Tornado", "Cyclone",
    "Cloud", "Mist", "Fog", "Dew", "Frost", "Sun", "Moon", "Star", "Planet", "Comet",
    "Asteroid", "Sky", "Horizon", "Aurora", "Eclipse", "Volcano", "Crater", "Lava", "Rock", "Stone",
    "Sand", "Earth", "Soil", "Clay", "Mineral", "Crystal", "Quartz", "Coal", "Iron", "Gold",
    "Silver", "Copper", "Plant", "Flower", "Leaf", "Root", "Seed", "Trunk", "Branch", "Bark",
    "Moss", "Algae", "Fungus", "Coral", "Reef", "Savanna", "Tundra", "Taiga", "Biome", "Ecosystem",
    //5. Lugares
    "City", "Town", "Village", "Neighborhood", "Street", "Avenue", "Square", "Park", "Garden", "Bridge",
    "Tunnel", "Highway", "Road", "Crossroad", "Roundabout", "Downtown", "Suburb", "District", "Capital", "Region",
    "Country", "State", "Province", "Continent", "Map", "Border", "Port", "Airport", "Station", "Terminal",
    "Hospital", "Clinic", "Pharmacy", "School", "College", "University", "Library", "Museum", "Theater", "Cinema",
    "Church", "Temple", "Sanctuary", "Monastery", "Cathedral", "Palace", "Castle", "Fortress", "Tower", "Monument",
    "Hotel", "Inn", "Hostel", "Restaurant", "Cafe", "Bar", "Market", "Fair", "Store", "Mall",
    "Factory", "Warehouse", "Depot", "Workshop", "Office", "Company", "Industry", "Bank", "Post Office", "Registry",
    "Police Station", "Barracks", "Court", "City Hall", "Council", "Stadium", "Gymnasium", "Arena", "Pool", "Gym",
    "Zoo", "Aquarium", "Observatory", "Planetarium", "Laboratory", "Cemetery", "Garage", "Parking Lot", "Bus Terminal", "Gas Station",
    //6. Animals
    "Bee", "Eagle", "Moose", "Spider", "Whale", "Butterfly", "Dog", "Camel", "Kangaroo", "Horse",
    "Snake", "Rabbit", "Owl", "Crocodile", "Elephant", "Squirrel", "Falcon", "Rooster", "Cat", "Giraffe",
    "Dolphin", "Hamster", "Hippopotamus", "Alligator", "Lion", "Leopard", "Wolf", "Otter", "Monkey", "Bat",
    "Jaguar", "Sheep", "Panda", "Parrot", "Duck", "Peacock", "Fish", "Penguin", "Pig", "Frog",
    "Fox", "Rat", "Rhinoceros", "Toad", "Serpent", "Turtle", "Tiger", "Shark", "Bear", "Cow",
    "Deer", "Zebra", "Crab", "Starfish", "Lobster", "Octopus", "Jellyfish", "Snail", "Lizard", "Iguana",
    "Ant", "Beetle", "Ladybug", "Scorpion", "Ray", "Eel", "Tuna", "Sardine", "Seagull", "Swallow",
    "Raven", "Dove", "Swan", "Goose", "Chicken", "Turkey", "Quail", "Boar", "Badger", "Weasel",
    "Seal", "Sea Lion", "Walrus", "Antelope", "Buffalo", "Bison", "Meerkat", "Lemur", "Orangutan", "Chimpanzee",
    //7. Fantasy Elements
    "Dragon", "Phoenix", "Unicorn", "Griffin", "Chimera", "Hydra", "Kraken", "Giant", "Dwarf", "Elf",
    "Orc", "Goblin", "Troll", "Demon", "Angel", "Seraph", "Titan", "Spirit", "Ghost", "Specter",
    "Shadows", "Light", "Darkness", "Magic", "Spell", "Enchantment", "Curse", "Runes", "Relic", "Artifact",
    "Amulet", "Talisman", "Staff", "Wand", "Grimoire", "Scroll", "Potion", "Elixir", "Crystal", "Obsidian",
    "Mithril", "Adamantium", "Aether", "Mana", "Essence", "Energy", "Portal", "Dimension", "Realm", "Empire",
    "Throne", "Crown", "Prophecy", "Destiny", "Chaos", "Order", "Balance", "Abyss", "Vortex", "Labyrinth",
    "Tower", "Fortress", "Citadel", "Temple", "Sanctuary", "Altar", "Lightning", "Flame", "Ice", "Ogre",
    "Wand", "Fairy", "Ancient", "Blood", "Bone", "Scale", "Wing", "Claw", "Eye", "Mask",
    "Sword", "Axe", "Bow", "Arrow", "Shield", "Armor", "Blade", "Hammer", "Orb", "Sigil",
    //8. Emotions
    "Joy", "Sadness", "Anger", "Fear", "Disgust", "Surprise", "Love", "Hate", "Hope", "Despair",
    "Anxiety", "Calm", "Peace", "Tension", "Pride", "Shame", "Guilt", "Relief", "Euphoria", "Melancholy",
    "Loneliness", "Longing", "Empathy", "Compassion", "Envy", "Jealousy", "Admiration", "Respect", "Trust", "Distrust",
    "Courage", "Cowardice", "Determination", "Doubt", "Faith", "Skepticism", "Gratitude", "Frustration", "Satisfaction", "Disappointment",
    "Enthusiasm", "Apathy", "Curiosity", "Boredom", "Interest", "Fascination", "Nostalgia", "Acceptance", "Rejection", "Humiliation",
    "Regret", "Remorse", "Pleasure", "Pain", "Comfort", "Discomfort", "Awe", "Dread", "Panic", "Serenity",
    "Shyness", "Optimism", "Pessimism", "Motivation", "Discouragement", "Affection", "Fondness", "Rage", "Resentment", "Bitterness",
    "Confusion", "Clarity", "Vanity", "Understanding", "Tolerance", "Irritation", "Exhaustion", "Relief", "Delight", "Wonder",
    //9. Body Parts
    "Head", "Face", "Forehead", "Eyebrow", "Eyelid", "Nose", "Mouth", "Lip", "Tooth", "Tongue",
    "Jaw", "Chin", "Cheek", "Ear", "Neck", "Nape", "Throat", "Clavicle", "Shoulder", "Armpit",
    "Arm", "Forearm", "Elbow", "Wrist", "Hand", "Palm", "Finger", "Nail", "Thumb", "Index",
    "Middle", "Ring", "Pinky", "Thorax", "Chest", "Rib", "Abdomen", "Belly", "Navel", "Hip",
    "Waist", "Groin", "Back", "Lower Back", "Spine", "Scapula", "Pelvis", "Buttock", "Thigh", "Knee",
    "Calf", "Shin", "Ankle", "Heel", "Foot", "Sole", "Instep", "Big Toe", "Joint", "Cartilage",
    "Muscle", "Tendon", "Ligament", "Skin", "Pores", "Vein", "Artery", "Lung", "Heart", "Stomach",
    "Liver", "Kidney", "Intestine", "Esophagus", "Trachea", "Larynx", "Diaphragm", "Pancreas", "Spleen", "Bladder",
    "Brain", "Spinal Cord", "Nerve", "Gland", "Hormone", "Retina", "Iris", "Cornea", "Pupil", "Meninges",
    //10. Music and musical instruments
    "Music", "Melody", "Harmony", "Rhythm", "Beat", "Tone", "Note", "Chord", "Scale", "Silence",
    "Sound", "Echo", "Volume", "Vibration", "Lyrics", "Chorus", "Verse", "Song", "Album", "Concert",
    "Orchestra", "Band", "Choir", "Conductor", "Singer", "Composer", "Performer", "Musician", "Producer", "Artist",
    "Piano", "Keyboard", "Organ", "Violin", "Viola", "Cello", "Double Bass", "Guitar", "Acoustic Guitar", "Bass",
    "Drums", "Drum", "Snare", "Cymbal", "Xylophone", "Marimba", "Flute", "Piccolo", "Clarinet", "Oboe",
    "Saxophone", "Trumpet", "Trombone", "Tuba", "Cornet", "Harmonica", "Accordion", "Mandolin", "Ukulele", "Harp",
    "Lyre", "Sitar", "Banjo", "Tambourine", "Berimbau", "Percussion", "Orchestration", "Improvisation", "Composition", "Arrangement",
    //11. Human relationships
    "Friendship", "Enmity", "Partnership", "Alliance", "Rivalry", "Competition", "Cooperation", "Conflict", "Bond", "Solidarity",
    "Love", "Passion", "Affection", "Attachment", "Distance", "Separation", "Union", "Marriage", "Divorce", "Family",
    "Relative", "Sibling", "Parenthood", "Motherhood", "Fatherhood", "Kinship", "Care", "Protection", "Support", "Trust",
    "Lover", "Couple", "Companion", "Partner", "Ex", "Crush", "Suitor", "Boss", "Employee", "Colleague",
    "Associate", "Client", "Supplier", "Leader", "Follower", "Mentor", "Apprentice", "Ally", "Enemy", "Traitor",
    "Accomplice", "Witness", "Stranger", "Acquaintance", "Neighbor", "Guest", "Host", "Rival", "Mediator", "Opponent",
    //12. Technology
    "Technology", "Machine", "System", "Device", "Appliance", "Equipment", "Tool", "Mechanism", "Circuit", "Processor",
    "Computer", "Server", "Terminal", "Console", "Laptop", "Tablet", "Phone", "Smartphone", "Screen", "Monitor",
    "Keyboard", "Mouse", "Sensor", "Camera", "Microphone", "Speaker", "Headphones", "Battery", "Charger", "Cable",
    "Network", "Internet", "Connection", "Signal", "Satellite", "Antenna", "Cloud", "Database", "File", "Storage",
    "Software", "Application", "Program", "Algorithm", "Code", "Script", "Interface", "Platform", "Operating System", "Update",
    "Firewall", "Encryption", "Security", "Privacy", "Leak", "Backup", "Automation", "Robot", "Artificial Intelligence", "Simulation",
    //13. Abstract, moral and philosophical concepts
    "Justice", "Injustice", "Truth", "Lie", "Good", "Evil", "Ethics", "Morality", "Virtue", "Sin",
    "Freedom", "Oppression", "Right", "Duty", "Responsibility", "Guilt", "Innocence", "Judgment", "Forgiveness", "Redemption",
    "Life", "Death", "Birth", "End", "Beginning", "Fate", "Chance", "Choice", "Consequence", "Meaning",
    "Existence", "Consciousness", "Identity", "Ego", "Soul", "Spirit", "Will", "Desire", "Intention", "Purpose",
    "Time", "Eternity", "Infinity", "Void", "Nothingness", "Totality", "Chaos", "Order", "Balance", "Rupture",
    "Apocalypse", "Collapse", "Creation", "Destruction", "Renewal", "Hope", "Despair", "Fear", "Courage", "Faith",
    //14. Hand tools
    "Hammer", "Sledgehammer", "Mallet", "Wrench", "Adjustable Wrench", "Screwdriver", "Phillips Screwdriver", "Pliers", "Cutting Pliers", "Locking Pliers",
    "Handsaw", "Hacksaw", "File", "Chisel", "Plane", "Tape Measure", "Level", "Square", "Compass", "Ruler",
    "Utility Knife", "Pocket Knife", "Scissors", "Clamp", "C Clamp", "Vise", "Punch", "Cold Chisel", "Spatula", "Trowel",
    "Shovel", "Hoe", "Pickaxe", "Rake", "Sickle", "Axe", "Rubber Mallet", "Wire Brush", "Sandpaper", "Scraper",
    //15. Machines
    "Machine", "Motor", "Engine", "Generator", "Compressor", "Lathe", "Milling Machine", "Press", "Conveyor", "Elevator",
    "Crane", "Excavator", "Backhoe", "Tractor", "Harvester", "Concrete Mixer", "Crusher", "Drilling Machine", "Drill", "Screwdriver Machine",
    "Electric Saw", "Circular Saw", "Band Saw", "Polisher", "Sander", "Planer", "Welding Machine", "Inverter", "Transformer", "Control Panel",
    "Pump", "Valve", "Fan", "Turbine", "Boiler", "Reactor", "3D Printer", "Industrial Robot", "CNC Machine", "Controller",
    //16. Buildings
    "House", "Building", "Apartment", "Duplex", "Warehouse", "Factory", "Workshop", "Store", "School", "Hospital",
    "Clinic", "Church", "Temple", "Cathedral", "Chapel", "Castle", "Fortress", "Palace", "Tower", "Bridge",
    "Viaduct", "Tunnel", "Road", "Highway", "Dam", "Dike", "Port", "Airport", "Station", "Terminal",
    "Stadium", "Gymnasium", "Arena", "Theater", "Cinema", "Museum", "Library", "Mall", "Market", "Fair",
    "Hotel", "Inn", "Hostel", "Restaurant", "Bar", "Cafe", "Gas Station", "Garage", "Parking Structure", "Depot",
    //17. Rooms
    "Room", "Living Room", "Dining Room", "Bedroom", "Suite", "Kitchen", "Pantry", "Bathroom", "Restroom", "Laundry Room",
    "Service Area", "Office", "Library", "Studio", "Workshop Room", "Closet", "Hallway", "Hall", "Entrance", "Balcony",
    "Terrace", "Attic", "Basement", "Cellar", "Garage", "Storage Room", "Utility Room", "File Room", "Anteroom", "Dressing Room",
    "Children Room", "Guest Room", "Game Room", "Meeting Room", "Control Room", "Technical Room", "Warehouse Room", "Archive", "Lobby", "Back Room",
    //18. Construction materials
    "Concrete", "Cement", "Sand", "Gravel", "Mortar", "Lime", "Plaster", "Stucco", "Putty", "Asphalt",
    "Brick", "Block", "Slab", "Beam", "Column", "Rebar", "Steel", "Iron", "Aluminum", "Copper",
    "Wood", "Plywood", "MDF", "OSB", "Plastic", "PVC", "Glass", "Fiber", "Rubber", "Insulation",
    "Roof Tile", "Ceramic", "Porcelain Tile", "Tile", "Granite", "Marble", "Stone", "Slate", "Quartz", "Coating",
    "Paint", "Varnish", "Sealer", "Waterproofing", "Glue", "Adhesive", "Screw", "Nail", "Wall Plug", "Ring",
    //19. Colors
    "White", "Black", "Gray", "Silver", "Gold",
    "Red", "Blue", "Green", "Yellow", "Orange", "Purple", "Pink", "Brown",
    "Beige", "Cream", "Wine", "Burgundy", "Turquoise", "Cyan", "Magenta",
    "Indigo", "Violet", "Lilac", "Lavender", "Olive", "Moss", "Emerald",
    "Sapphire", "Amber", "Caramel", "Chocolate", "Sand", "Graphite",
    "Coral", "Peach", "Salmon", "Mustard", "Rust",
    "Light blue", "Dark blue", "Light green", "Dark green", "Light gray", "Dark gray",
    //20. Physical states
    "Solid", "Liquid", "Gas", "Plasma",
    "Hard", "Soft", "Rigid", "Flexible", "Elastic",
    "Fragile", "Resistant", "Broken", "Intact", "Damaged",
    "Smooth", "Rough", "Porous", "Polished",
    "Dry", "Wet", "Damp", "Soaked",
    "Hot", "Cold", "Frozen", "Warm",
    "Heavy", "Light", "Dense", "Hollow", "Solid mass",
    "Transparent", "Opaque", "Translucent",
    "Open", "Closed", "Locked", "Unlocked",
    "Full", "Empty", "Cracked", "Bent", "Folded",
    "Stable", "Unstable", "Fixed", "Movable",
    "New", "Used", "Old", "Ancient", "Rusty",
    //21. Sports and sporting goods
    "Soccer", "Basketball", "Volleyball", "Handball", "Futsal", "Tennis", "Table tennis", "Badminton", "Baseball", "Softball",
    "Rugby", "Cricket", "Hockey", "Ice hockey", "Field hockey", "Golf", "Polo", "Bowling", "Bocce", "Peteca",
    "Swimming", "Diving", "Water polo", "Surfing", "Windsurfing", "Kitesurfing", "Skateboarding", "Roller skating", "Cycling", "Mountain biking",
    "Athletics", "Running", "Marathon", "Jumping", "Throwing",
    "Boxing", "Judo", "Karate", "Taekwondo", "Jiu-jitsu", "Fencing", "Wrestling", "Muay thai",
    "Climbing", "Mountaineering", "Skiing", "Snowboarding",
    "Ball", "Soccer ball", "Basketball ball", "Racket", "Tennis racket", "Ping pong paddle",
    "Bat", "Stick", "Glove", "Helmet", "Shin guard", "Knee pad", "Elbow pad",
    "Net", "Goal", "Hoop", "Target", "Track", "Court", "Field",
    //22. Hobbies
    "Reading", "Writing", "Drawing", "Painting", "Illustration", "Sculpture", "Graffiti",
    "Photography", "Filming", "Editing", "Animation",
    "Music", "Singing", "Composition", "Instrument", "Acoustic guitar", "Electric guitar", "Piano", "Keyboard", "Drums",
    "Games", "Video game", "Board game", "Card game", "RPG", "Puzzle",
    "Programming", "Coding", "Modeling", "3D printing",
    "Crafting", "Crochet", "Knitting", "Sewing", "Embroidery", "Woodworking", "Ceramics",
    "Cooking", "Baking", "Confectionery",
    "Gardening", "Horticulture", "Cultivation",
    "Observation", "Astronomy", "Telescope",
    "Collecting", "Miniatures", "Stamps", "Coins", "Cards",
    "Origami", "Calligraphy", "Chess", "Checkers", "Sudoku",
    "Meditation", "Yoga", "Walking", "Hiking", "Camping",
    //23. Means of transportation
    "Car", "Automobile", "Truck", "Pickup", "Bus", "Minibus", "Van",
    "Motorcycle", "Scooter", "Bicycle", "Tricycle", "Quadricycle",
    "Train", "Subway", "Railcar", "Locomotive", "Tram", "Monorail",
    "Airplane", "Jet", "Seaplane", "Glider", "Helicopter", "Airship",
    "Ship", "Boat", "Speedboat", "Yacht", "Ferry", "Canoe", "Kayak", "Submarine",
    "Cargo ship", "Oil tanker", "Aircraft carrier",
    "Kick scooter", "Hoverboard",
    "Electric car", "Hybrid car",
    "Sled", "Cable car", "Funicular",
    "Cart", "Carriage",
    "Spaceship", "Rocket", "Space shuttle",
    "Balloon",
    //24. Clothing
    "T-shirt", "Blouse", "Tank top", "Sweater", "Pullover",
    "Dress", "Skirt", "Shorts", "Bermuda shorts", "Jumpsuit",
    "Suit", "Blazer", "Vest", "Overcoat", "Poncho",
    "Pajamas", "Bathrobe", "Uniform",
    "Underwear", "Briefs", "Panties", "Bra",
    "Tights", "Leggings",
    "Bikini", "Swimsuit", "Swim briefs",
    "Sneakers", "Boots", "Flip flops", "Sandals", "Flats", "Combat boots",
    "Gloves", "Scarf", "Necktie", "Bow tie",
    "Bracelet", "Necklace", "Ring", "Earring",
    "Hood", "Beanie",
    "Apron", "Military uniform", "Costume"
];